/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DMI;

import java.awt.Component;
import java.sql.*;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
/**
 *
 * @author coner
 */
public class BuscarEmpleado extends javax.swing.JInternalFrame {
public int BEindice;
public DefaultTableModel tbBEres;

    /**
     * Creates new form BuscarEmpleado
     */
    public BuscarEmpleado() {
        initComponents();
        this.setIconifiable(true);
        spanBEres.getVerticalScrollBar().setUnitIncrement(16);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIEregresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panBE = new javax.swing.JPanel();
        txtBEnss = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtBEmatricula = new javax.swing.JTextField();
        txtBEnombre = new javax.swing.JTextField();
        txtBEcorreo = new javax.swing.JTextField();
        cboxBEempresa = new javax.swing.JComboBox<>();
        txtBEcurp = new javax.swing.JTextField();
        txtBErfc = new javax.swing.JTextField();
        btnBEmodificar = new javax.swing.JButton();
        btnBEbaja = new javax.swing.JButton();
        btnBEbuscar = new javax.swing.JButton();
        spanBEres = new javax.swing.JScrollPane();
        tbBEconsulta = new javax.swing.JTable();

        setTitle("Buscar Empleado");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnIEregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_arrow_back_grey600_18dp.png"))); // NOI18N
        btnIEregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIEregresarActionPerformed(evt);
            }
        });

        panBE.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Empleado"));

        jLabel8.setText("NSS:");

        jLabel7.setText("RFC:");

        jLabel6.setText("CURP:");

        jLabel4.setText("Empresa:");

        jLabel3.setText("Correo:");

        jLabel2.setText("Nombre:");

        jLabel1.setText("Matrícula:");

        cboxBEempresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Empresa", "SERCON", "ICC", "SAMSARA", "MABA" }));

        btnBEmodificar.setText("Modificar Empleado");
        btnBEmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBEmodificarActionPerformed(evt);
            }
        });

        btnBEbaja.setText("Dar de baja");
        btnBEbaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBEbajaActionPerformed(evt);
            }
        });

        btnBEbuscar.setText("Buscar Empleado");
        btnBEbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBEbuscarActionPerformed(evt);
            }
        });

        tbBEconsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sus resultados se mostrarán aquí:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbBEconsulta.getTableHeader().setReorderingAllowed(false);
        spanBEres.setViewportView(tbBEconsulta);
        if (tbBEconsulta.getColumnModel().getColumnCount() > 0) {
            tbBEconsulta.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout panBELayout = new javax.swing.GroupLayout(panBE);
        panBE.setLayout(panBELayout);
        panBELayout.setHorizontalGroup(
            panBELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panBELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBELayout.createSequentialGroup()
                        .addGroup(panBELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spanBEres, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panBELayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBEcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panBELayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBEmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panBELayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBEnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panBELayout.createSequentialGroup()
                        .addGroup(panBELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panBELayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboxBEempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panBELayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBEcurp, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panBELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panBELayout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtBEnss))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panBELayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtBErfc, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panBELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBEbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBEmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBEbaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59))))
        );
        panBELayout.setVerticalGroup(
            panBELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panBELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBEmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panBELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBEnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panBELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBEcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panBELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panBELayout.createSequentialGroup()
                        .addGroup(panBELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cboxBEempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panBELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtBEcurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panBELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtBErfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panBELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtBEnss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panBELayout.createSequentialGroup()
                        .addComponent(btnBEbuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBEmodificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBEbaja)))
                .addGap(18, 18, 18)
                .addComponent(spanBEres, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(panBE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIEregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIEregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*btnIEregresarActionPerformed closes the current window
      Doesn't use global variables.
      Doesn't use local variables. */
    private void btnIEregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIEregresarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnIEregresarActionPerformed

    /*btnBEmodificarActionPerformed from the current data selected, it generate a new window to modify it
      Doesn't use global variables.
      Doesn't use local variables. */
    private void btnBEmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBEmodificarActionPerformed
        try {
            BEindice=Integer.parseInt(tbBEconsulta.getValueAt(tbBEconsulta.getSelectedRow(),0).toString());
            ModificarEmpleado ME = new ModificarEmpleado(BEindice);
            JDesktopPane desktopPane = getDesktopPane();
            desktopPane.add(ME);
            ME.show();
        } catch(Exception e)    {
            JOptionPane.showMessageDialog(null,"No tiene nada seleccionado.","Selección vacía",2);
        }
    }//GEN-LAST:event_btnBEmodificarActionPerformed

    
    /*consultarDatos consults data from the database
      Doesn't use global variables.
      Doesn't use local variables. */
    private void consultarDatos()
    {
        String[]encabezados={"Matricula","Nombre","Apellidos", "Direccion","Correo","Empresa","Puesto","CURP","NSS","Celular","Teléfono","RFC","Tel Emergencia","Contacto de Referencia","Correo del Contacto","Estado"};
        String[]filas=new String[16];
        
        tbBEres=new DefaultTableModel(null,encabezados);
        
        ConexionMySQL cmysql=new ConexionMySQL();
        Connection conec=cmysql.Conectar();
        
        String empresa = "";
        if(cboxBEempresa.getSelectedIndex()!=0)    {
           empresa = String.valueOf(cboxBEempresa.getSelectedItem());
        }
        if(cboxBEempresa.getSelectedIndex()==0)    {
           empresa = "";
        }
        
        String senSQL="SELECT empleado.matricula as \"Matricula\",\n" +
            "empleado.nombreEmpleado as \"Nombre\",\n" +
            "CONCAT(COALESCE(empleado.apellidoPaternoEmpleado,''), ' ', COALESCE(empleado.apellidoMaternoEmpleado,'')) as \"Apellidos\",\n" +
            "CONCAT (COALESCE(direccion.calle,''), ' ', COALESCE(direccion.numeroExterior,'N/A'), ' ',\n" +
            "  COALESCE(direccion.numeroInterior,'N/A'), ', Col. ', COALESCE(direccion.colonia,''), ', ',\n" +
            "  COALESCE(direccion.codigoPostal,''), ' ', COALESCE(alcaldia.alcaldia,''), ', ',\n" +
            "  COALESCE(ciudad.nombre,'')) as \"Direccion\",\n" +
            "empleado.correoEmpleado as \"Correo\", empresa.nombre as \"Empresa\",\n" +
            "puesto.nombre as \"Puesto\", empleado.curp as \"CURP\",\n" +
            "empleado.numeroSeguroSocial as \"NSS\", empleado.celular as \"Celular\",\n" +
            "empleado.telefono as \"Telefono\", empleado.RFC as \"RFC\",\n" +
            "empleado.telefonoEmergencia as \"Tel Emergencia\",\n" +
            "CONCAT(COALESCE(empleado.nombreContacto,''), ' ',\n" +
            "  COALESCE(empleado.apellidoPaternoContacto,''), ' ',\n" +
            "  COALESCE(empleado.apellidoMaternoContacto,'')) as \"Contacto de Referencia\",\n" +
            "empleado.correoContacto as \"Correo del Contacto\",\n" +
            "empleado.estadoActivo as \"Activo\"\n" +
            "FROM empleado, empresa, puesto, direccionEmpleado, direccion, alcaldia, ciudad\n" +
            "WHERE empleado.empresa=empresa.clave\n" +
            "AND puesto.clave=empleado.puesto AND empleado.matricula=direccionEmpleado.claveEmpleado\n" +
            "AND direccion.clave=direccionEmpleado.claveDireccion AND alcaldia.clave=direccion.alcaldia\n" +
            "AND ciudad.clave=alcaldia.claveCiudad" +
            //LIKE
            "  AND Matricula LIKE '%"+txtBEmatricula.getText()+"%'\n" +
            "  AND CONCAT(COALESCE(empleado.nombreEmpleado,''),' ',COALESCE(empleado.apellidoPaternoEmpleado,''),' ', COALESCE(empleado.apellidoMaternoEmpleado,'')) LIKE '%"+txtBEnombre.getText()+"%'\n" +
            "  AND empleado.correoEmpleado LIKE '%"+txtBEcorreo.getText()+"%'\n" +
            "  AND empresa.nombre LIKE '%"+empresa+"%'\n" +
            "  AND empleado.curp LIKE '%"+txtBEcurp.getText()+"%'\n" +
            "  AND empleado.RFC LIKE '%"+txtBErfc.getText()+"%'\n" +
            "  AND empleado.numeroSeguroSocial LIKE '%"+txtBEnss.getText()+"%'\n" +
            "ORDER BY empleado.matricula;";
        
        try{
            Statement st=conec.createStatement();
            ResultSet rs=st.executeQuery(senSQL);
            
            while(rs.next()){
                filas[0]=rs.getString("Matricula");
                filas[1]=rs.getString("Nombre");
                filas[2]=rs.getString("Apellidos");
                filas[3]=rs.getString("Direccion");
                filas[4]=rs.getString("Correo");
                filas[5]=rs.getString("Empresa");
                filas[6]=rs.getString("Puesto");
                filas[7]=rs.getString("CURP");
                filas[8]=rs.getString("NSS");
                filas[9]=rs.getString("Celular");
                filas[10]=rs.getString("Telefono");
                filas[11]=rs.getString("RFC");
                filas[12]=rs.getString("Tel Emergencia");
                filas[13]=rs.getString("Contacto de Referencia");
                filas[14]=rs.getString("Correo del Contacto");
                if(rs.getString("Activo").equals("0"))   {
                    filas[15]="Inactivo";
                }
                if(rs.getString("Activo").equals("1"))   {
                    filas[15]="Activo";
                }
                tbBEres.addRow(filas);
            }
            this.tbBEconsulta.setModel(tbBEres);
            this.tbBEconsulta.setDefaultEditor(Object.class, null);
            
            // Ajustar el tamaño de las columnas
            tbBEconsulta.setAutoResizeMode(tbBEconsulta.AUTO_RESIZE_OFF);
            /*TableColumnAdjuster tca = new TableColumnAdjuster(tbBEconsulta);
            tca.adjustColumns();*/
            for (int column = 0; column < tbBEconsulta.getColumnCount(); column++)
            {
                TableColumn tableColumn = tbBEconsulta.getColumnModel().getColumn(column);
                int preferredWidth = tableColumn.getMinWidth();
                int maxWidth = tableColumn.getMaxWidth();

                for (int row = 0; row < tbBEconsulta.getRowCount(); row++)
                {
                    TableCellRenderer cellRenderer = tbBEconsulta.getCellRenderer(row, column);
                    Component c = tbBEconsulta.prepareRenderer(cellRenderer, row, column);
                    int width = c.getPreferredSize().width + tbBEconsulta.getIntercellSpacing().width;
                    preferredWidth = Math.max(preferredWidth, width);

                    //  We've exceeded the maximum width, no need to check other rows

                    if (preferredWidth >= maxWidth)
                    {
                        preferredWidth = maxWidth;
                        break;
                    }
                }
                tableColumn.setPreferredWidth( preferredWidth );
            }
            
        }catch(SQLException ex){
                JOptionPane.showMessageDialog(null,ex);
        }
    }

    /*btnBEbajaActionPerformed changes the employee's status from estadoActivo to 0 in the database
      Doesn't use global variables.
      Doesn't use local variables. */
    private void btnBEbajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBEbajaActionPerformed
        BEindice=Integer.parseInt(tbBEconsulta.getValueAt(tbBEconsulta.getSelectedRow(),0).toString());
        System.out.println(BEindice);
        ConexionMySQL cmysql = new ConexionMySQL();
        Connection conec = (Connection) cmysql.Conectar();
        try {
            String senSQL = "UPDATE empleado SET estadoActivo = 0 WHERE matricula = "+BEindice;
            String a = tbBEconsulta.getValueAt(tbBEconsulta.getSelectedRow(),15).toString();
            if(a.equals("Activo"))    {
                try {
                    PreparedStatement ps = conec.prepareStatement(senSQL);
                    int n=ps.executeUpdate();
                    if (n>0)    {
                        JOptionPane.showOptionDialog(this, "Se dado de baja el empleado satisfactoriamente",
                                "MySQL Information", JOptionPane.INFORMATION_MESSAGE,
                                JOptionPane.INFORMATION_MESSAGE, null, new Object[]{" 0K "},"0K");
                        consultarDatos();
                    }
                } catch (Exception ex)  {
                    JOptionPane.showMessageDialog(null,ex,"Error",0);
                }
            }
            if(a.equals("Inactivo"))    {
                JOptionPane.showOptionDialog(this, "El empleado seleccionado actualmente está inactivo.",
                            "MySQL Information", JOptionPane.INFORMATION_MESSAGE,
                            JOptionPane.INFORMATION_MESSAGE, null, new Object[]{" 0K "},"0K");
            }
        } catch(Exception e)    {
            JOptionPane.showMessageDialog(null,"No tiene nada seleccionado.","Selección vacía",2);
            System.out.println(e);
        }
        
    }//GEN-LAST:event_btnBEbajaActionPerformed

    /*btnBEbuscarActionPerformed 
      Doesn't use global variables.
      Doesn't use local variables. */
    private void btnBEbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBEbuscarActionPerformed
        consultarDatos();
    }//GEN-LAST:event_btnBEbuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBEbaja;
    private javax.swing.JButton btnBEbuscar;
    private javax.swing.JButton btnBEmodificar;
    private javax.swing.JButton btnIEregresar;
    private javax.swing.JComboBox<String> cboxBEempresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panBE;
    private javax.swing.JScrollPane spanBEres;
    private javax.swing.JTable tbBEconsulta;
    private javax.swing.JTextField txtBEcorreo;
    private javax.swing.JTextField txtBEcurp;
    private javax.swing.JTextField txtBEmatricula;
    private javax.swing.JTextField txtBEnombre;
    private javax.swing.JTextField txtBEnss;
    private javax.swing.JTextField txtBErfc;
    // End of variables declaration//GEN-END:variables
}