/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DMI;

import java.awt.*;
import java.io.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author coner
 */
public class IngresarEmpleado extends javax.swing.JInternalFrame {

public String IEnombre_de_empleado;
public String IEapellido_paterno_empleado;
public String IEapellido_materno_empleado;
public String IEcorreo;
public int IEempresa;
public int IEpuesto;
protected String IEcurp;
protected String IErfc;
protected String IEnss;
public String IEcelular;
public String IEtelefono;
protected String IEtelefono_emergencia;
public int IEpais;
public int IEestado;
public int IEciudad;
public int IEalcaldia;
protected String IEnumero_exterior;
protected String IEnumero_interior;
protected String IEcalle;
protected String IEcolonia;
protected int IEcodigo_postal;
protected String IEnombre_contacto;
protected String IEapellido_paterno_contacto;
protected String IEapellido_materno_contacto;
protected String IEcorreo_contacto;
protected boolean IEvigente;
protected int IEmatricula;

public int IEtipo;

protected File IEf;
protected FileInputStream IEfoto = null;
protected Image IEfi = null;

static FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "png", "gif", "jpeg");
static Comprobacion c = new Comprobacion();
/**
     * Creates new form IngresarEmpleado
     */
    public IngresarEmpleado() {
        initComponents();
        this.setIconifiable(true);
        
        try {
            ConexionMySQL cmysql = new ConexionMySQL();
            Connection conec = (Connection) cmysql.Conectar();
            Statement st=conec.createStatement();
            ResultSet rs = st.executeQuery("SELECT pais FROM pais;");
            while (rs.next())   {
                this.cboxIEpais.addItem(rs.getString("pais"));
            }
        } catch(Exception ex)   {
            JOptionPane.showMessageDialog(null,ex,"SQL error",2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIEregresar = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtIEnombre_de_empleado = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtIEcorreo = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        cboxIEempresa = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        txtIEcurp = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtIErfc = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtIEnss = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtIEcelular = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtIEtelefono = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtIEtelefono_emergencia = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtIEnombre_contacto = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtIEcorreo_contacto = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        lblIEno_vigente = new javax.swing.JLabel();
        tgbIEvigente = new javax.swing.JToggleButton();
        lblIEvigente = new javax.swing.JLabel();
        btnIEguardar = new javax.swing.JButton();
        btnIEcancelar = new javax.swing.JButton();
        btnIEfoto = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        txtIEapellido_paterno_empleado = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtIEapellido_materno_empleado = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtIEapellido_paterno_contacto = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txtIEapellido_materno_contacto = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        cboxIEpuesto = new javax.swing.JComboBox<>();
        jLabel45 = new javax.swing.JLabel();
        cboxIEpais = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        cboxIEestado = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        txtIEnumero_exterior = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtIEnumero_interior = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txtIEcalle = new javax.swing.JTextField();
        txtIEcolonia = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        txtIEcodigo_postal = new javax.swing.JTextField();
        cboxIEciudad = new javax.swing.JComboBox<>();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        cboxIEalcaldia = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();

        setIconifiable(true);
        setMaximizable(true);
        setTitle("Ingresar empleado");

        btnIEregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_arrow_back_grey600_18dp.png"))); // NOI18N
        btnIEregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIEregresarActionPerformed(evt);
            }
        });

        jLabel23.setText("Nombre:");

        jLabel24.setText("Correo:");

        jLabel25.setText("Empresa:");

        cboxIEempresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Empresa", "SERCON", "ICC", "SAMSARA", "MABA" }));

        jLabel27.setText("CURP:");

        jLabel28.setText("RFC:");

        jLabel29.setText("Número de Seguro Social:");

        jLabel30.setText("Teléfono celular:");

        jLabel31.setText("Teléfono:");

        txtIEtelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIEtelefonoActionPerformed(evt);
            }
        });

        jLabel32.setText("Teléfono emergencia:");

        jLabel33.setText("Nombre:");

        jLabel34.setText("Correo de contacto:");

        jLabel35.setText("Status:");

        lblIEno_vigente.setText("No vigente");

        tgbIEvigente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_check_box_black_18dp.png"))); // NOI18N
        tgbIEvigente.setSelected(true);
        tgbIEvigente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgbIEvigenteActionPerformed(evt);
            }
        });

        lblIEvigente.setText("Vigente");

        btnIEguardar.setText("Guardar");
        btnIEguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIEguardarActionPerformed(evt);
            }
        });

        btnIEcancelar.setText("Cancelar");
        btnIEcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIEcancelarActionPerformed(evt);
            }
        });

        btnIEfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MódulosAcceso/Módulos/add_photo.png"))); // NOI18N
        btnIEfoto.setText("Foto");
        btnIEfoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIEfoto.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnIEfoto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIEfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIEfotoActionPerformed(evt);
            }
        });

        jLabel36.setText("Apellido Paterno:");

        jLabel37.setText("Apellido Materno:");

        jLabel38.setText("Apellido Paterno:");

        txtIEapellido_paterno_contacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIEapellido_paterno_contactoActionPerformed(evt);
            }
        });

        jLabel39.setText("Apellido Materno:");

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel43.setText("Datos del empleado");

        jLabel44.setText("Puesto:");

        cboxIEpuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Puesto", "Directivo", "Secretaria", "Técnico" }));
        cboxIEpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxIEpuestoActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel45.setText("Dirección del empleado");

        cboxIEpais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un país" }));
        cboxIEpais.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxIEpaisItemStateChanged(evt);
            }
        });
        cboxIEpais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxIEpaisActionPerformed(evt);
            }
        });

        jLabel26.setText("País:");

        jLabel40.setText("Estado:");

        cboxIEestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un estado" }));
        cboxIEestado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxIEestadoItemStateChanged(evt);
            }
        });

        jLabel41.setText("Número exterior:");

        jLabel42.setText("Número interior:");

        jLabel46.setText("Calle:");

        jLabel47.setText("Colonia:");

        jLabel48.setText("Código Postal:");

        cboxIEciudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la ciudad" }));

        jLabel49.setText("Ciudad:");

        jLabel50.setText("Alcaldía:");

        cboxIEalcaldia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la alcaldía" }));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Contacto del empleado");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIEnombre_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIEapellido_paterno_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIEapellido_materno_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel49, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel50, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cboxIEciudad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboxIEestado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboxIEpais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboxIEalcaldia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(102, 102, 102)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel47, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtIEcodigo_postal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtIEnumero_interior, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIEcalle, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIEcolonia, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIEnumero_exterior)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIEcorreo_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIEnss, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(128, 128, 128)
                                    .addComponent(tgbIEvigente, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblIEvigente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnIEcancelar)
                                    .addGap(29, 29, 29)
                                    .addComponent(btnIEguardar))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addGap(220, 220, 220)
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addComponent(jLabel19)
                                                        .addComponent(jLabel45)
                                                        .addComponent(jLabel43)))
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel27)
                                                        .addComponent(jLabel28))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtIEcurp, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                                        .addComponent(txtIErfc)))
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                        .addComponent(jLabel44)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(cboxIEpuesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addComponent(jLabel25)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(cboxIEempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGap(125, 125, 125))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel23)
                                                .addComponent(jLabel24))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(txtIEnombre_de_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(txtIEcorreo)
                                                    .addGap(46, 46, 46)))
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                    .addComponent(jLabel37)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtIEapellido_materno_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                    .addComponent(jLabel36)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtIEapellido_paterno_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(18, 18, 18)))
                                    .addComponent(btnIEfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(33, 33, 33)
                        .addComponent(lblIEno_vigente))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIEcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIEtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIEtelefono_emergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(txtIEnombre_de_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIEcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25)
                                    .addComponent(cboxIEempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel44)
                                    .addComponent(cboxIEpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27)
                                    .addComponent(txtIEcurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel36)
                                    .addComponent(txtIEapellido_paterno_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel37)
                                    .addComponent(txtIEapellido_materno_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIErfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)))
                    .addComponent(btnIEfoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtIEnss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtIEcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtIEtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txtIEtelefono_emergencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel45)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(cboxIEpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(txtIEnumero_exterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(cboxIEestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42)
                    .addComponent(txtIEnumero_interior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(cboxIEciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46)
                    .addComponent(txtIEcalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(cboxIEalcaldia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47)
                    .addComponent(txtIEcolonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(txtIEcodigo_postal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txtIEnombre_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38)
                    .addComponent(txtIEapellido_paterno_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(txtIEapellido_materno_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtIEcorreo_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel35)
                                .addComponent(lblIEno_vigente))
                            .addComponent(tgbIEvigente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnIEcancelar)
                                .addComponent(btnIEguardar))
                            .addGap(1, 1, 1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblIEvigente)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jScrollPane.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIEregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIEregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(467, Short.MAX_VALUE))
            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void ingresar()  {
        
        try {
            ConexionMySQL cmysql = new ConexionMySQL();
            Connection conec = (Connection) cmysql.Conectar();

            String senSQL = "INSERT INTO empleado (nombreEmpleado,apellidoPaternoEmpleado,apellidoMaternoEmpleado,correoEmpleado,empresa,puesto,curp,numeroSeguroSocial,celular,telefonoEmergencia,nombreContacto,apellidoPaternoContacto,apellidoMaternoContacto,correoContacto,estadoActivo,telefono,fotoEmpleado,RFC) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            String senSQL2 = "INSERT INTO direccion (numeroExterior,numeroInterior,calle,colonia,codigoPostal,tipo,alcaldia) VALUES(?,?,?,?,?,?,?)";

            PreparedStatement ps = conec.prepareStatement(senSQL);
        
            ps.setString(1,IEnombre_de_empleado);
            ps.setString(2,IEapellido_paterno_empleado);
            ps.setString(3,IEapellido_materno_empleado);
            ps.setString(4,IEcorreo);
            ps.setInt(5,IEempresa);
            ps.setInt(6,IEpuesto);
            ps.setString(7,IEcurp);
            ps.setString(8,IEnss);
            ps.setString(9,IEcelular);
            ps.setString(10,IEtelefono_emergencia);
            ps.setString(11,IEnombre_contacto);
            ps.setString(12,IEapellido_paterno_contacto);
            ps.setString(13,IEapellido_materno_contacto);
            ps.setString(14,IEcorreo_contacto);
            ps.setBoolean(15,IEvigente);
            ps.setString(16,IEtelefono);
            ps.setBinaryStream(17,IEfoto);
            ps.setString(18,IErfc);
            
            PreparedStatement ps2 = conec.prepareStatement(senSQL2);
            ps2.setString(1,IEnumero_exterior);
            ps2.setString(2,IEnumero_interior);
            ps2.setString(3,IEcalle);
            ps2.setString(4,IEcolonia);
            ps2.setInt(5,IEcodigo_postal);
            ps2.setInt(6,IEtipo);
            ps2.setInt(7,IEalcaldia);
            
            PreparedStatement ps3 = conec.prepareStatement("INSERT INTO direccionEmpleado VALUES((select max(matricula) from empleado),(select max(clave) from direccion))");
            PreparedStatement ps4 = conec.prepareStatement("UPDATE empleado SET contrasena = (select max(matricula)+1000) WHERE matricula=(select max(matricula)) AND RFC='"+IErfc+"'");
            int m = ps2.executeUpdate();
            int n = ps.executeUpdate();
            int o = ps3.executeUpdate();
            int p = ps4.executeUpdate();
            Statement st = conec.createStatement();
            ResultSet rs = st.executeQuery("SELECT MAX(matricula) FROM EMPLEADO");
            while(rs.next()) {
                IEmatricula = rs.getInt("MAX(matricula)");
            }
            if (n > 0 && m > 0 && o > 0 && p > 0)  {
                JOptionPane.showOptionDialog(this, "Se han guardado sus datos satisfactoriamente. La contraseña es la matricula + 1000.",
                        "MySQL Information", JOptionPane.INFORMATION_MESSAGE,
                        JOptionPane.INFORMATION_MESSAGE, null, new Object[]{" 0K "},"0K");
                this.dispose();
            }
        }
        catch( SQLException ex )    {
            JOptionPane.showMessageDialog(null,ex,"SQL error",2);
        }
    }

    
    private void btnIEregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIEregresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnIEregresarActionPerformed

    private void btnIEfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIEfotoActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(filter);
        chooser.showOpenDialog(null);
        IEf = chooser.getSelectedFile();
        try {
            IEfoto = new FileInputStream(IEf);
            IEfi=Toolkit.getDefaultToolkit().createImage(IEf.getAbsolutePath());
            IEfi=IEfi.getScaledInstance(144, 144, 1);
            btnIEfoto.setIcon(new ImageIcon(IEfi));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(IngresarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIEfotoActionPerformed

    private void btnIEcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIEcancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnIEcancelarActionPerformed

    private void btnIEguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIEguardarActionPerformed
        IEnombre_de_empleado = this.txtIEnombre_de_empleado.getText().trim();
        IEapellido_paterno_empleado = this.txtIEapellido_paterno_empleado.getText().trim();
        IEapellido_materno_empleado = this.txtIEapellido_materno_empleado.getText().trim();
        IEcorreo = this.txtIEcorreo.getText().trim();
        IEempresa = this.cboxIEempresa.getSelectedIndex();
        IEpuesto = this.cboxIEempresa.getSelectedIndex();
        IEcurp = this.txtIEcurp.getText().trim();
        IEnss = this.txtIEnss.getText().trim();
        IEcelular = this.txtIEcelular.getText().trim();
        IEtelefono_emergencia = this.txtIEtelefono_emergencia.getText().trim();
        IEnombre_contacto = this.txtIEnombre_contacto.getText().trim();
        IEapellido_paterno_contacto = this.txtIEapellido_paterno_contacto.getText().trim();
        IEapellido_materno_contacto = this.txtIEapellido_materno_contacto.getText().trim();
        IEcorreo_contacto = this.txtIEcorreo_contacto.getText().trim();
        IEvigente = this.tgbIEvigente.isSelected();
        IEtelefono = this.txtIEtelefono.getText().trim();
        IErfc = this.txtIErfc.getText().trim();
        
        IEnumero_exterior = this.txtIEnumero_exterior.getText().trim();
        IEnumero_interior = this.txtIEnumero_interior.getText().trim();
        IEcalle = this.txtIEcalle.getText().trim();
        IEcolonia = this.txtIEcolonia.getText().trim();
        IEcodigo_postal = Integer.parseInt(this.txtIEcodigo_postal.getText().trim());
        IEtipo = 4;
        IEalcaldia = this.cboxIEalcaldia.getSelectedIndex();
        
        String pr="";
        
        if(c.valtext(IEnombre_de_empleado)&&c.valtext(IEapellido_paterno_empleado)&&c.valtext(IEapellido_materno_empleado)&&
                c.valmail(IEcorreo)&&IEempresa!=0&&IEpuesto!=0&&c.valcurp(IEcurp)&&c.valnss(IEnss)&&c.valcel(IEcelular)&&
                c.valtel(IEtelefono_emergencia)&&c.valtext(IEnombre_contacto)&&c.valtext(IEapellido_paterno_contacto)&&
                c.valtext(IEapellido_materno_contacto)&&c.valmail(IEcorreo_contacto)&&c.valtel(IEtelefono)&&
                c.valrfc(IErfc)&&c.valne(IEnumero_exterior)&&c.valni(IEnumero_interior)&&!c.vacio(IEcalle)&&
                c.valtext(IEcolonia)&&c.valcp(this.txtIEcodigo_postal.getText().trim())&&IEalcaldia!=0)    {
            ingresar();
        }
        if(!c.valtext(IEnombre_de_empleado)) {
            pr=pr+"\nNombre del empleado";
        }
        if(!c.valtext(IEapellido_paterno_empleado))    {
            pr=pr+"\nApellido paterno del empleado";
        }
        if(!c.valtext(IEapellido_materno_empleado))    {
            pr=pr+"\nApellido materno del empleado";
        }
        if(!c.valmail(IEcorreo))    {
            pr=pr+"\nCorreo del empleado";
        }
        if(IEempresa==0)    {
            pr=pr+"\nEmpresa";
        }
        if(IEpuesto==0)    {
            pr=pr+"\nPuesto";
        }
        if(!c.valcurp(IEcurp))    {
            pr=pr+"\nCURP";
        }
        if(!c.valnss(IEnss))    {
            pr=pr+"\nNúmero de Seguridad Social";
        }
        if(!c.valcel(IEcelular))    {
            pr=pr+"\nCelular";
        }
        if(!c.valtel(IEtelefono_emergencia))    {
            pr=pr+"\nTeléfono de emergencia";
        }
        if(!c.valtext(IEnombre_contacto))    {
            pr=pr+"\nNombre del contacto";
        }
        if(!c.valtext(IEapellido_paterno_contacto))    {
            pr=pr+"\nApellido paterno del contacto";
        }
        if(!c.valtext(IEapellido_materno_contacto))    {
            pr=pr+"\nApellido materno del contacto";
        }
        if(!c.valmail(IEcorreo_contacto)) {
            pr=pr+"\nCorreo del contacto";
        }
        if(!c.valtel(IEtelefono))   {
            pr=pr+"\nTeléfono";
        }
        if(!c.valrfc(IErfc))    {
            pr=pr+"\nRFC";
        }
        if(!c.valne(IEnumero_exterior))    {
            pr=pr+"\nNúmero exterior";
        }
        if(!c.valni(IEnumero_interior))    {
            pr=pr+"\nNúmero interior";
        }
        if(c.vacio(IEcalle))    {
            pr=pr+"\nCalle";
        }
        if(!c.valtext(IEcolonia))    {
            pr=pr+"\nColonia";
        }
        if(!c.valcp(this.txtIEcodigo_postal.getText().trim()))    {
            pr=pr+"\nCódigo Postal";
        }
        if(IEalcaldia==0)    {
            pr=pr+"\nAlcaldía";
        }
        if(!(c.valtext(IEnombre_de_empleado)&&c.valtext(IEapellido_paterno_empleado)&&c.valtext(IEapellido_materno_empleado)&&
                c.valmail(IEcorreo)&&IEempresa!=0&&IEpuesto!=0&&c.valcurp(IEcurp)&&c.valnss(IEnss)&&c.valcel(IEcelular)&&
                c.valtel(IEtelefono_emergencia)&&c.valtext(IEnombre_contacto)&&c.valtext(IEapellido_paterno_contacto)&&
                c.valtext(IEapellido_materno_contacto)&&c.valmail(IEcorreo_contacto)&&c.valtel(IEtelefono)&&
                c.valrfc(IErfc)&&c.valne(IEnumero_exterior)&&c.valni(IEnumero_interior)&&!c.vacio(IEcalle)&&
                c.valtext(IEcolonia)&&c.valcp(this.txtIEcodigo_postal.getText().trim())&&IEalcaldia!=0))    {
            JOptionPane.showMessageDialog(null, "Revice los siguientes campos e inténtelo de nuevo: "+pr, "Datos incorrectos", 2);
        }
    }//GEN-LAST:event_btnIEguardarActionPerformed

    private void tgbIEvigenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgbIEvigenteActionPerformed
        if(tgbIEvigente.isSelected())   {
            tgbIEvigente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_check_box_black_18dp.png")));
        }
        else    {
            tgbIEvigente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_check_box_outline_blank_black_18dp.png")));
        }
    }//GEN-LAST:event_tgbIEvigenteActionPerformed

    private void txtIEtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIEtelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIEtelefonoActionPerformed

    private void txtIEapellido_paterno_contactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIEapellido_paterno_contactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIEapellido_paterno_contactoActionPerformed

    private void cboxIEpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxIEpuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxIEpuestoActionPerformed

    private void cboxIEpaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxIEpaisActionPerformed

    }//GEN-LAST:event_cboxIEpaisActionPerformed

    private void cboxIEestadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxIEestadoItemStateChanged
        this.cboxIEalcaldia.removeAllItems();
        this.cboxIEalcaldia.addItem("Seleccione la alcaldía");
        ConexionMySQL cmysql = new ConexionMySQL();
        Connection conec = (Connection) cmysql.Conectar();
        
        try {
            Statement st=conec.createStatement();
            ResultSet rs = st.executeQuery("SELECT alcaldia FROM alcaldia WHERE claveCiudad = "+cboxIEestado.getSelectedIndex());
            while (rs.next())   {
                this.cboxIEalcaldia.addItem(rs.getString("alcaldia"));
            }
        } catch(Exception ex)   {
            JOptionPane.showMessageDialog(null,ex,"SQL error",2);
        }
    }//GEN-LAST:event_cboxIEestadoItemStateChanged

    private void cboxIEpaisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxIEpaisItemStateChanged
        this.cboxIEestado.removeAllItems();
        this.cboxIEestado.addItem("Seleccione un estado");
        ConexionMySQL cmysql = new ConexionMySQL();
        Connection conec = (Connection) cmysql.Conectar();
        
        try {
            Statement st=conec.createStatement();
            ResultSet rs = st.executeQuery("SELECT estado FROM estado WHERE clavePais = "+cboxIEpais.getSelectedIndex());
            while (rs.next())   {
                this.cboxIEestado.addItem(rs.getString("estado"));
            }
        } catch(Exception ex)   {
            JOptionPane.showMessageDialog(null,ex,"SQL error",2);
        }
    }//GEN-LAST:event_cboxIEpaisItemStateChanged
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIEcancelar;
    private javax.swing.JButton btnIEfoto;
    private javax.swing.JButton btnIEguardar;
    private javax.swing.JButton btnIEregresar;
    private javax.swing.JComboBox<String> cboxIEalcaldia;
    private javax.swing.JComboBox<String> cboxIEciudad;
    private javax.swing.JComboBox<String> cboxIEempresa;
    private javax.swing.JComboBox<String> cboxIEestado;
    private javax.swing.JComboBox<String> cboxIEpais;
    private javax.swing.JComboBox<String> cboxIEpuesto;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblIEno_vigente;
    private javax.swing.JLabel lblIEvigente;
    private javax.swing.JToggleButton tgbIEvigente;
    private javax.swing.JTextField txtIEapellido_materno_contacto;
    private javax.swing.JTextField txtIEapellido_materno_empleado;
    private javax.swing.JTextField txtIEapellido_paterno_contacto;
    private javax.swing.JTextField txtIEapellido_paterno_empleado;
    private javax.swing.JTextField txtIEcalle;
    private javax.swing.JTextField txtIEcelular;
    private javax.swing.JTextField txtIEcodigo_postal;
    private javax.swing.JTextField txtIEcolonia;
    private javax.swing.JTextField txtIEcorreo;
    private javax.swing.JTextField txtIEcorreo_contacto;
    private javax.swing.JTextField txtIEcurp;
    private javax.swing.JTextField txtIEnombre_contacto;
    private javax.swing.JTextField txtIEnombre_de_empleado;
    private javax.swing.JTextField txtIEnss;
    private javax.swing.JTextField txtIEnumero_exterior;
    private javax.swing.JTextField txtIEnumero_interior;
    private javax.swing.JTextField txtIErfc;
    private javax.swing.JTextField txtIEtelefono;
    private javax.swing.JTextField txtIEtelefono_emergencia;
    // End of variables declaration//GEN-END:variables
}
