/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DMI;

import java.sql.*;
import javax.swing.*;

/**
 *
 * @author coner
 */
public class IngresarCliente extends javax.swing.JInternalFrame {

public String ICnombre_de_cliente;
public String ICtelefono_oficina;
public int ICempresa;
public String ICextension;
protected String ICnombre_del_representante;
protected String ICapellido_paterno_representante;
protected String ICapellido_materno_representante;
protected String ICcorreo_del_representante;
protected String ICcorreo_empresarial;
protected String ICrfc;
protected boolean ICvigente;

public int ICpais;
public int ICestado;
public int ICciudad;
public int ICalcaldia;
protected String ICnumero_exterior;
protected String ICnumero_interior;
protected String ICcalle;
protected String ICcolonia;
protected int ICcodigo_postal;

protected int ICmatricula;

static Comprobacion c = new Comprobacion();

    /**
     * Creates new form IngresarCliente
     */
    public IngresarCliente() {
        initComponents();
        ConexionMySQL cmysql = new ConexionMySQL();
        Connection conec = (Connection) cmysql.Conectar();
        
        try {
            Statement st=conec.createStatement();
            ResultSet rs = st.executeQuery("SELECT pais FROM pais");
            while (rs.next())   {
                this.cboxICpais.addItem(rs.getString("pais"));
            }
        } catch(Exception ex)   {
            JOptionPane.showMessageDialog(null,ex,"SQL error",2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIEregresar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        txtICnombre_cliente = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        cboxICempresa = new javax.swing.JComboBox<>();
        jLabel61 = new javax.swing.JLabel();
        txtICnumero_exterior = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        txtICtelefono_oficina = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        txtICextension = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        txtICnombre_del_representante = new javax.swing.JTextField();
        txtICcorreo_del_representante = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        txtICcorreo_empresarial = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        txtICrfc = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        btnICcancelar = new javax.swing.JButton();
        btnICguardar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cboxICpais = new javax.swing.JComboBox<>();
        cboxICestado = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cboxICciudad = new javax.swing.JComboBox<>();
        cboxICalcaldia = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtICnumero_interior = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtICcalle = new javax.swing.JTextField();
        txtICcolonia = new javax.swing.JTextField();
        txtICcodigo_postal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtICapellido_paterno_representante = new javax.swing.JTextField();
        txtICapellido_materno_representante = new javax.swing.JTextField();
        tgbICvigente = new javax.swing.JToggleButton();

        btnIEregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_arrow_back_grey600_18dp.png"))); // NOI18N
        btnIEregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIEregresarActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Nuevo Cliente"));

        jLabel59.setText("Empresa cliente:");

        jLabel60.setText("Empresa a quien pertenece:");

        cboxICempresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Empresa", "SERCON", "ICC", "SAMSARA", "MABA" }));

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel61.setText("Dirección del cliente");

        txtICnumero_exterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtICnumero_exteriorActionPerformed(evt);
            }
        });

        jLabel62.setText("Teléfono de oficina:");

        jLabel63.setText("Extensión telefónica:");

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel64.setText("Contacto del representante");

        jLabel65.setText("Nombre:");

        jLabel66.setText("Correo representante:");

        txtICnombre_del_representante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtICnombre_del_representanteActionPerformed(evt);
            }
        });

        jLabel67.setText("Correo empresarial:");

        txtICcorreo_empresarial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtICcorreo_empresarialActionPerformed(evt);
            }
        });

        jLabel68.setText("RFC:");

        jLabel71.setText("Vigencia");

        jLabel72.setText("Status:");

        jLabel73.setText("No vigente");

        jLabel74.setText("Vigente");

        btnICcancelar.setText("Cancelar");
        btnICcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnICcancelarActionPerformed(evt);
            }
        });

        btnICguardar.setText("Guardar");
        btnICguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnICguardarActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Información del cliente");

        jLabel21.setText("País:");

        jLabel22.setText("Estado:");

        cboxICpais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un país" }));
        cboxICpais.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxICpaisItemStateChanged(evt);
            }
        });

        cboxICestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un estado" }));
        cboxICestado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxICestadoItemStateChanged(evt);
            }
        });

        jLabel23.setText("Ciudad:");

        jLabel24.setText("Alcaldía:");

        cboxICciudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la ciudad" }));

        cboxICalcaldia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la alcaldía" }));

        jLabel25.setText("Número exterior:");

        jLabel26.setText("Número interior:");

        jLabel27.setText("Calle:");

        jLabel28.setText("Colonia:");

        jLabel29.setText("Código Postal:");

        jLabel1.setText("Apellido Paterno:");

        jLabel2.setText("Apellido Materno:");

        tgbICvigente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_check_box_black_18dp.png"))); // NOI18N
        tgbICvigente.setSelected(true);
        tgbICvigente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgbICvigenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnICcancelar)
                                .addGap(18, 18, 18)
                                .addComponent(btnICguardar))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel65)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(txtICnombre_del_representante, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtICapellido_paterno_representante, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtICapellido_materno_representante, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel67)
                                    .addComponent(jLabel66))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtICcorreo_empresarial)
                                    .addComponent(txtICcorreo_del_representante, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel68)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtICrfc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel72)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel73)
                                .addGap(18, 18, 18)
                                .addComponent(tgbICvigente, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel74))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel71)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cboxICciudad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboxICestado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboxICpais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboxICalcaldia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(102, 102, 102)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtICnumero_exterior)
                    .addComponent(txtICnumero_interior)
                    .addComponent(txtICcalle)
                    .addComponent(txtICcolonia)
                    .addComponent(txtICcodigo_postal))
                .addGap(24, 24, 24))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel62)
                            .addComponent(jLabel59))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtICtelefono_oficina, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(txtICnombre_cliente))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel63)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtICextension, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel60)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboxICempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel61)
                            .addComponent(jLabel20)
                            .addComponent(jLabel64))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(txtICnombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel60)
                    .addComponent(cboxICempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(txtICtelefono_oficina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel63)
                    .addComponent(txtICextension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel61)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cboxICpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(txtICnumero_exterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cboxICestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(txtICnumero_interior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(cboxICciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(txtICcalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(cboxICalcaldia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(txtICcolonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtICcodigo_postal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel64)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel65)
                    .addComponent(txtICnombre_del_representante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtICapellido_paterno_representante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtICapellido_materno_representante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66)
                    .addComponent(txtICcorreo_del_representante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtICcorreo_empresarial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel67))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68)
                    .addComponent(txtICrfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel71)
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel72)
                            .addComponent(jLabel73))
                        .addComponent(tgbICvigente, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel74)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnICcancelar)
                    .addComponent(btnICguardar))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIEregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIEregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ingresar()  {
        
        ConexionMySQL cmysql = new ConexionMySQL();
        Connection conec = (Connection) cmysql.Conectar();
        
        String senSQL = "INSERT INTO cliente(vigencia,nombreEmpresa,correoEmpresarial,extension,telefonoOficina,nombreRepresentante,apellidoPaternoRepresentante,apellidoMaternoRepresentante,correoRepresentante,empresa,RFC) VALUES(?,?,?,?,?,?,?,?,?,?,?)";
        String senSQL2 = "INSERT INTO direccion (numeroExterior,numeroInterior,calle,colonia,codigoPostal,tipo,alcaldia) VALUES(?,?,?,?,?,?,?)";

        try {
            
            PreparedStatement ps = conec.prepareStatement(senSQL);
            ps.setBoolean(1,ICvigente);
            ps.setString(2,ICnombre_de_cliente);
            ps.setString(3,ICcorreo_empresarial);
            ps.setString(4,ICextension);
            ps.setString(5,ICtelefono_oficina);
            ps.setString(6,ICnombre_del_representante);
            ps.setString(7,ICapellido_paterno_representante);
            ps.setString(8,ICapellido_materno_representante);
            ps.setString(9,ICcorreo_del_representante);
            ps.setInt(10,ICempresa);
            ps.setString(11,ICrfc);
            
            PreparedStatement ps2 = conec.prepareStatement(senSQL2);
            ps2.setString(1,ICnumero_exterior);
            ps2.setString(2,ICnumero_interior);
            ps2.setString(3,ICcalle);
            ps2.setString(4,ICcolonia);
            ps2.setInt(5,ICcodigo_postal);
            ps2.setInt(6,1);
            ps2.setInt(7,ICalcaldia);
            
            PreparedStatement ps3 = conec.prepareStatement("INSERT INTO direccionCliente VALUES((select max(folio) from cliente),(select max(clave) from direccion))");
            PreparedStatement ps4 = conec.prepareStatement("UPDATE cliente SET contrasena = (select max(folio)+1000) WHERE matricula=(select max(folio)) AND RFC='"+ICrfc+"'");
            int m = ps2.executeUpdate();
            int n = ps.executeUpdate();
            int o = ps3.executeUpdate();
            int p = ps4.executeUpdate();
            Statement st = conec.createStatement();
            ResultSet rs = st.executeQuery("SELECT MAX(matricula) FROM EMPLEADO");
            while(rs.next()) {
                ICmatricula = rs.getInt("MAX(matricula)");
            }
            if (n > 0 && m > 0 && o > 0 && p > 0)  {
                JOptionPane.showOptionDialog(this, "Se han guardado sus datos satisfactoriamente. La contraseña es la matricula + 1000.",
                        "MySQL Information", JOptionPane.INFORMATION_MESSAGE,
                        JOptionPane.INFORMATION_MESSAGE, null, new Object[]{" 0K "},"0K");
                this.dispose();
            }
        }
        catch( SQLException ex )    {
            JOptionPane.showMessageDialog(null,ex,"SQL error",2);
        }
    }
    
    private void btnIEregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIEregresarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnIEregresarActionPerformed

    private void txtICnumero_exteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtICnumero_exteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtICnumero_exteriorActionPerformed

    private void txtICnombre_del_representanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtICnombre_del_representanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtICnombre_del_representanteActionPerformed

    private void txtICcorreo_empresarialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtICcorreo_empresarialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtICcorreo_empresarialActionPerformed

    private void btnICcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnICcancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnICcancelarActionPerformed

    private void tgbICvigenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgbICvigenteActionPerformed
        if(tgbICvigente.isSelected())   {
            tgbICvigente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_check_box_black_18dp.png")));
        }
        else    {
            tgbICvigente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_check_box_outline_blank_black_18dp.png")));
        }
    }//GEN-LAST:event_tgbICvigenteActionPerformed

    private void btnICguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnICguardarActionPerformed
        ICnombre_de_cliente = this.txtICnombre_cliente.getText().trim();
        ICtelefono_oficina = this.txtICtelefono_oficina.getText().trim();
        ICempresa = this.cboxICempresa.getSelectedIndex();
        ICextension = this.txtICextension.getText().trim();
        ICnombre_del_representante = this.txtICnombre_del_representante.getText().trim();
        ICapellido_paterno_representante = this.txtICapellido_paterno_representante.getText().trim();
        ICapellido_materno_representante = this.txtICapellido_materno_representante.getText().trim();
        ICcorreo_del_representante = this.txtICcorreo_del_representante.getText().trim();
        ICcorreo_empresarial = this.txtICcorreo_empresarial.getText().trim();
        ICrfc = this.txtICrfc.getText().trim();
        ICvigente = this.tgbICvigente.isSelected();
        
        ICnumero_exterior = this.txtICnumero_exterior.getText().trim();
        ICnumero_interior = this.txtICnumero_interior.getText().trim();
        ICcalle = this.txtICcalle.getText().trim();
        ICcolonia = this.txtICcolonia.getText().trim();
        ICcodigo_postal = Integer.parseInt(this.txtICcodigo_postal.getText().trim());
        ICalcaldia = this.cboxICalcaldia.getSelectedIndex();
        
        String pr="";
        
        if(c.valtext(ICnombre_de_cliente)&&c.valmail(ICcorreo_empresarial)&&ICempresa!=0&&c.valtext(ICnombre_del_representante)&&
                c.valtext(ICapellido_paterno_representante)&&c.valtext(ICapellido_materno_representante)&&c.valmail(ICcorreo_del_representante)&&
                c.valtel(ICtelefono_oficina)&&c.valrfc(ICrfc)&&c.valne(ICnumero_exterior)&&c.valni(ICnumero_interior)&&!c.vacio(ICcalle)&&
                c.valtext(ICcolonia)&&c.valcp(this.txtICcodigo_postal.getText().trim())&&ICalcaldia!=0&&c.valint(ICextension))    {
            ingresar();
        }
        if(!c.valtext(ICnombre_de_cliente)) {
            pr=pr+"\nNombre de la empresa cliente";
        }
        if(!c.valmail(ICcorreo_empresarial))    {
            pr=pr+"\nCorreo empresarial";
        }
        if(ICempresa==0)    {
            pr=pr+"\nEmpresa";
        }
        if(!c.valtext(ICnombre_del_representante))    {
            pr=pr+"\nNombre del representante";
        }
        if(!c.valtext(ICapellido_paterno_representante))    {
            pr=pr+"\nApellido paterno del representante";
        }
        if(!c.valtext(ICapellido_materno_representante))    {
            pr=pr+"\nApellido materno del representante";
        }
        if(!c.valmail(ICcorreo_del_representante)) {
            pr=pr+"\nCorreo del representante";
        }
        if(!c.valtel(ICtelefono_oficina))   {
            pr=pr+"\nTeléfono de oficina";
        }
        if(!c.valrfc(ICrfc))    {
            pr=pr+"\nRFC";
        }
        if(!c.valne(ICnumero_exterior))    {
            pr=pr+"\nNúmero exterior";
        }
        if(!c.valni(ICnumero_interior))    {
            pr=pr+"\nNúmero interior";
        }
        if(c.vacio(ICcalle))    {
            pr=pr+"\nCalle";
        }
        if(!c.valtext(ICcolonia))    {
            pr=pr+"\nColonia";
        }
        if(!c.valcp(this.txtICcodigo_postal.getText().trim()))    {
            pr=pr+"\nCódigo Postal";
        }
        if(ICalcaldia==0)    {
            pr=pr+"\nAlcaldía";
        }
        if(!c.valint(ICextension))   {
            pr=pr+"\nExtensión";
        }
        if(!(c.valtext(ICnombre_de_cliente)&&c.valmail(ICcorreo_empresarial)&&ICempresa!=0&&c.valtext(ICnombre_del_representante)&&
                c.valtext(ICapellido_paterno_representante)&&c.valtext(ICapellido_materno_representante)&&c.valmail(ICcorreo_del_representante)&&
                c.valtel(ICtelefono_oficina)&&c.valrfc(ICrfc)&&c.valne(ICnumero_exterior)&&c.valni(ICnumero_interior)&&!c.vacio(ICcalle)&&
                c.valtext(ICcolonia)&&c.valcp(this.txtICcodigo_postal.getText().trim())&&ICalcaldia!=0)&&c.valint(ICextension))    {
            JOptionPane.showMessageDialog(null, "Revice los siguICntes campos e inténtelo de nuevo: "+pr, "Datos incorrectos", 2);
        }
    }//GEN-LAST:event_btnICguardarActionPerformed

    private void cboxICpaisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxICpaisItemStateChanged
        this.cboxICestado.removeAllItems();
        this.cboxICestado.addItem("Seleccione un estado");
        ConexionMySQL cmysql = new ConexionMySQL();
        Connection conec = (Connection) cmysql.Conectar();
        
        try {
            Statement st=conec.createStatement();
            ResultSet rs = st.executeQuery("SELECT estado FROM estado WHERE clavePais = "+cboxICpais.getSelectedIndex());
            while (rs.next())   {
                this.cboxICestado.addItem(rs.getString("estado"));
            }
        } catch(Exception ex)   {
            JOptionPane.showMessageDialog(null,ex,"SQL error",2);
        }
    }//GEN-LAST:event_cboxICpaisItemStateChanged

    private void cboxICestadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxICestadoItemStateChanged
        this.cboxICalcaldia.removeAllItems();
        this.cboxICalcaldia.addItem("Seleccione la alcaldía");
        ConexionMySQL cmysql = new ConexionMySQL();
        Connection conec = (Connection) cmysql.Conectar();
        
        try {
            Statement st=conec.createStatement();
            ResultSet rs = st.executeQuery("SELECT alcaldia FROM alcaldia WHERE claveCiudad = "+cboxICestado.getSelectedIndex());
            while (rs.next())   {
                this.cboxICalcaldia.addItem(rs.getString("alcaldia"));
            }
        } catch(Exception ex)   {
            JOptionPane.showMessageDialog(null,ex,"SQL error",2);
        }
    }//GEN-LAST:event_cboxICestadoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnICcancelar;
    private javax.swing.JButton btnICguardar;
    private javax.swing.JButton btnIEregresar;
    private javax.swing.JComboBox<String> cboxICalcaldia;
    private javax.swing.JComboBox<String> cboxICciudad;
    private javax.swing.JComboBox<String> cboxICempresa;
    private javax.swing.JComboBox<String> cboxICestado;
    private javax.swing.JComboBox<String> cboxICpais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton tgbICvigente;
    private javax.swing.JTextField txtICapellido_materno_representante;
    private javax.swing.JTextField txtICapellido_paterno_representante;
    private javax.swing.JTextField txtICcalle;
    private javax.swing.JTextField txtICcodigo_postal;
    private javax.swing.JTextField txtICcolonia;
    private javax.swing.JTextField txtICcorreo_del_representante;
    private javax.swing.JTextField txtICcorreo_empresarial;
    private javax.swing.JTextField txtICextension;
    private javax.swing.JTextField txtICnombre_cliente;
    private javax.swing.JTextField txtICnombre_del_representante;
    private javax.swing.JTextField txtICnumero_exterior;
    private javax.swing.JTextField txtICnumero_interior;
    private javax.swing.JTextField txtICrfc;
    private javax.swing.JTextField txtICtelefono_oficina;
    // End of variables declaration//GEN-END:variables
}
