/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DMI;

import java.awt.*;
import static java.awt.Color.*;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.event.KeyEvent;
import java.awt.geom.RoundRectangle2D;
import java.util.Arrays;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import net.java.balloontip.*;
import net.java.balloontip.styles.*;

/**
 *
 * @author coner
 */
public class Login extends javax.swing.JFrame {

protected String Lcorreo;
private static String Lcontra;
private String Lscontra, Lmail = "";
private int Lcodigo;
public int Lpuesto, Lmatricula, Lcont=0;
public int[] Lintentos = new int[40];
public int X1, Y1;
Comprobacion ALERTA = new Comprobacion();

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        dialogLrecuperar_contrasenha.setLocationRelativeTo(this);
        dialogLasignar_contrasenha.setLocationRelativeTo(this);
        setTitle("SASERCON");
        setIconImage(new ImageIcon(getClass().getResource("/img/LOGOfdktp.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogLasignar_contrasenha = new javax.swing.JDialog();
        panLcontraseña = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        psfLnueva_contra = new javax.swing.JPasswordField();
        psfLconfirmar_contra = new javax.swing.JPasswordField();
        lblLcerrar1 = new javax.swing.JLabel();
        btnLguardar = new javax.swing.JButton();
        btnLregresar = new javax.swing.JButton();
        dialogLrecuperar_contrasenha = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtLcodigo = new javax.swing.JTextField();
        btnLconfirmar = new javax.swing.JButton();
        lblLcerrar2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panLLogin = new javax.swing.JPanel();
        lblLcorreo = new javax.swing.JLabel();
        lblLcontra = new javax.swing.JLabel();
        btnLaccesar = new javax.swing.JButton();
        txtLcorreo = new javax.swing.JTextField();
        lblLlogo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        psfLcontra = new javax.swing.JPasswordField();
        lblLiusuario = new javax.swing.JLabel();
        lblLipassword = new javax.swing.JLabel();
        lblLcerrar = new javax.swing.JLabel();
        lblLminimizar = new javax.swing.JLabel();
        lblLrecuperar_contra = new javax.swing.JLabel();

        dialogLasignar_contrasenha.setMinimumSize(new java.awt.Dimension(390, 355));
        dialogLasignar_contrasenha.setUndecorated(true);
        dialogLasignar_contrasenha.setSize(new java.awt.Dimension(390, 355));
        dialogLasignar_contrasenha.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dialogLasignar_contrasenhaMouseDragged(evt);
            }
        });
        dialogLasignar_contrasenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dialogLasignar_contrasenhaMousePressed(evt);
            }
        });

        panLcontraseña.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));

        jLabel4.setText("Nueva Contraseña");

        jLabel5.setText("Confirmar Contraseña");

        jLabel6.setPreferredSize(new java.awt.Dimension(14, 14));

        jLabel7.setPreferredSize(new java.awt.Dimension(20, 20));

        psfLnueva_contra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                psfLnueva_contraKeyTyped(evt);
            }
        });

        psfLconfirmar_contra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                psfLconfirmar_contraKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panLcontraseñaLayout = new javax.swing.GroupLayout(panLcontraseña);
        panLcontraseña.setLayout(panLcontraseñaLayout);
        panLcontraseñaLayout.setHorizontalGroup(
            panLcontraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLcontraseñaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panLcontraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panLcontraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(psfLnueva_contra, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(psfLconfirmar_contra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panLcontraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        panLcontraseñaLayout.setVerticalGroup(
            panLcontraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLcontraseñaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panLcontraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panLcontraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(psfLnueva_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panLcontraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panLcontraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(psfLconfirmar_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblLcerrar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLcerrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogIn/icons8_close_window_24px_3.png"))); // NOI18N
        lblLcerrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLcerrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLcerrar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLcerrar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLcerrar1MouseExited(evt);
            }
        });

        btnLguardar.setText("Guardar y continuar>");
        btnLguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLguardarActionPerformed(evt);
            }
        });

        btnLregresar.setText("< Regresar");
        btnLregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLregresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogLasignar_contrasenhaLayout = new javax.swing.GroupLayout(dialogLasignar_contrasenha.getContentPane());
        dialogLasignar_contrasenha.getContentPane().setLayout(dialogLasignar_contrasenhaLayout);
        dialogLasignar_contrasenhaLayout.setHorizontalGroup(
            dialogLasignar_contrasenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panLcontraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogLasignar_contrasenhaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(dialogLasignar_contrasenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLcerrar1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogLasignar_contrasenhaLayout.createSequentialGroup()
                        .addComponent(btnLregresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLguardar))))
        );
        dialogLasignar_contrasenhaLayout.setVerticalGroup(
            dialogLasignar_contrasenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogLasignar_contrasenhaLayout.createSequentialGroup()
                .addComponent(lblLcerrar1)
                .addGap(1, 1, 1)
                .addComponent(panLcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(dialogLasignar_contrasenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLguardar)
                    .addComponent(btnLregresar)))
        );

        dialogLrecuperar_contrasenha.setMinimumSize(new java.awt.Dimension(410, 130));
        dialogLrecuperar_contrasenha.setUndecorated(true);
        dialogLrecuperar_contrasenha.setSize(new java.awt.Dimension(430, 130));

        jLabel8.setText("Se le ha enviado un código a su correo. Revíselo e ingrese el código aquí:");

        txtLcodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLcodigoKeyTyped(evt);
            }
        });

        btnLconfirmar.setText("Confirmar");
        btnLconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLconfirmarActionPerformed(evt);
            }
        });
        btnLconfirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnLconfirmarKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtLcodigo)
                        .addGap(18, 18, 18)
                        .addComponent(btnLconfirmar))
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLconfirmar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblLcerrar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLcerrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogIn/icons8_close_window_24px_3.png"))); // NOI18N
        lblLcerrar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLcerrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLcerrar2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLcerrar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLcerrar2MouseExited(evt);
            }
        });

        jLabel9.setText("Recuerde revisar en la carpeta de SPAM");

        javax.swing.GroupLayout dialogLrecuperar_contrasenhaLayout = new javax.swing.GroupLayout(dialogLrecuperar_contrasenha.getContentPane());
        dialogLrecuperar_contrasenha.getContentPane().setLayout(dialogLrecuperar_contrasenhaLayout);
        dialogLrecuperar_contrasenhaLayout.setHorizontalGroup(
            dialogLrecuperar_contrasenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogLrecuperar_contrasenhaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblLcerrar2))
            .addGroup(dialogLrecuperar_contrasenhaLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(dialogLrecuperar_contrasenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogLrecuperar_contrasenhaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addGap(5, 5, 5))
        );
        dialogLrecuperar_contrasenhaLayout.setVerticalGroup(
            dialogLrecuperar_contrasenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogLrecuperar_contrasenhaLayout.createSequentialGroup()
                .addComponent(lblLcerrar2)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panLLogin.setBackground(new java.awt.Color(232, 229, 224));
        panLLogin.setName(""); // NOI18N
        panLLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panLLoginMouseDragged(evt);
            }
        });
        panLLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panLLoginMousePressed(evt);
            }
        });

        lblLcorreo.setForeground(new java.awt.Color(120, 121, 124));
        lblLcorreo.setText("Correo:");

        lblLcontra.setForeground(new java.awt.Color(120, 121, 124));
        lblLcontra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLcontra.setText("Contraseña:");
        lblLcontra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnLaccesar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLaccesar.setForeground(new java.awt.Color(102, 102, 102));
        btnLaccesar.setText("Accesar");
        btnLaccesar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLaccesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaccesarActionPerformed(evt);
            }
        });

        txtLcorreo.setMaximumSize(new java.awt.Dimension(7, 20));
        txtLcorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLcorreoFocusLost(evt);
            }
        });
        txtLcorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLcorreoKeyTyped(evt);
            }
        });

        lblLlogo.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("../img/LogIn/LOGOf.png")).getImage().getScaledInstance(190, 190, Image.SCALE_DEFAULT)));
        lblLlogo.setMaximumSize(new java.awt.Dimension(155, 155));
        lblLlogo.setMinimumSize(new java.awt.Dimension(155, 155));
        lblLlogo.setPreferredSize(new java.awt.Dimension(155, 155));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(120, 121, 124));
        jLabel3.setText("Iniciar Sesión");

        psfLcontra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                psfLcontraKeyTyped(evt);
            }
        });

        lblLiusuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLiusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogIn/icons8_user_filled_30px.png"))); // NOI18N

        lblLipassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLipassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogIn/icons8_key_30px.png"))); // NOI18N

        lblLcerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLcerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogIn/icons8_close_window_24px_3.png"))); // NOI18N
        lblLcerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblLcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLcerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLcerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLcerrarMouseExited(evt);
            }
        });

        lblLminimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogIn/icons8_minimize_window_24px_1.png"))); // NOI18N
        lblLminimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblLminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLminimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLminimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLminimizarMouseExited(evt);
            }
        });

        lblLrecuperar_contra.setForeground(new java.awt.Color(51, 102, 255));
        lblLrecuperar_contra.setText("<HTML>¿Olvidaste tu contraseña?</HTML>");
        lblLrecuperar_contra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLrecuperar_contra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLrecuperar_contraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLrecuperar_contraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLrecuperar_contraMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panLLoginLayout = new javax.swing.GroupLayout(panLLogin);
        panLLogin.setLayout(panLLoginLayout);
        panLLoginLayout.setHorizontalGroup(
            panLLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panLLoginLayout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addGroup(panLLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panLLoginLayout.createSequentialGroup()
                        .addGroup(panLLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLcontra, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLcorreo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panLLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnLaccesar)
                            .addComponent(psfLcontra, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(lblLlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panLLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panLLoginLayout.createSequentialGroup()
                                .addGroup(panLLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLiusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLipassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(157, 157, 157))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLLoginLayout.createSequentialGroup()
                                .addComponent(lblLrecuperar_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLLoginLayout.createSequentialGroup()
                        .addComponent(lblLminimizar)
                        .addGap(0, 0, 0)
                        .addComponent(lblLcerrar))))
        );
        panLLoginLayout.setVerticalGroup(
            panLLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLLoginLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblLlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addGroup(panLLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtLcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLcorreo)
                    .addComponent(lblLiusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(panLLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblLipassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psfLcontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLcontra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLaccesar)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLLoginLayout.createSequentialGroup()
                .addGroup(panLLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLcerrar)
                    .addComponent(lblLminimizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLrecuperar_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panLLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panLLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(600, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblLcerrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLcerrar1MouseClicked
        dialogLasignar_contrasenha.dispose();
    }//GEN-LAST:event_lblLcerrar1MouseClicked

    private void lblLcerrar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLcerrar1MouseEntered
        lblLcerrar1.setIcon((Icon) new ImageIcon(getClass().getResource("../img/LogIn/icons8_close_window_24px_6.png")));
    }//GEN-LAST:event_lblLcerrar1MouseEntered

    private void lblLcerrar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLcerrar1MouseExited
        lblLcerrar1.setIcon((Icon) new ImageIcon(getClass().getResource("../img/LogIn/icons8_close_window_24px_3.png")));
    }//GEN-LAST:event_lblLcerrar1MouseExited

    private void btnLconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLconfirmarActionPerformed
        confirmarCodigo();
    }//GEN-LAST:event_btnLconfirmarActionPerformed

    private void lblLcerrar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLcerrar2MouseClicked
        dialogLrecuperar_contrasenha.dispose();
    }//GEN-LAST:event_lblLcerrar2MouseClicked

    private void lblLcerrar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLcerrar2MouseEntered
        lblLcerrar2.setIcon((Icon) new ImageIcon(getClass().getResource("../img/LogIn/icons8_close_window_24px_6.png")));
    }//GEN-LAST:event_lblLcerrar2MouseEntered

    private void lblLcerrar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLcerrar2MouseExited
        lblLcerrar2.setIcon((Icon) new ImageIcon(getClass().getResource("../img/LogIn/icons8_close_window_24px_3.png")));
    }//GEN-LAST:event_lblLcerrar2MouseExited

    private void btnLguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLguardarActionPerformed
        asignarContrasenha();
    }//GEN-LAST:event_btnLguardarActionPerformed

    private void btnLregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLregresarActionPerformed
        dialogLasignar_contrasenha.dispose();
    }//GEN-LAST:event_btnLregresarActionPerformed

    private void btnLconfirmarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLconfirmarKeyTyped
        char d=evt.getKeyChar();
        if(d == KeyEvent.VK_ENTER)  {
            if(ALERTA.valint(txtLcodigo.getText())) {
                System.out.println("prueba");
                System.out.println(txtLcodigo.getText());
                if(Lcodigo == Integer.parseInt(txtLcodigo.getText().trim()))  {
                    dialogLrecuperar_contrasenha.dispose();
                    LrecuperarContrasena();
                }
                else    {
                    JOptionPane.showMessageDialog(null,"Revise que el código corresponda con el enviado a su correo.","Código inválido",2);
                }
            }
            else    {
                JOptionPane.showMessageDialog(null,"El código está conformado de 8 dígitos numéricos.","Código inválido",2);
            }
        }
    }//GEN-LAST:event_btnLconfirmarKeyTyped

    private void panLLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panLLoginMousePressed
        X1 = evt.getX();
        Y1 = evt.getY();
    }//GEN-LAST:event_panLLoginMousePressed

    private void panLLoginMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panLLoginMouseDragged
        Point mueve = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(mueve.x - X1, mueve.y - Y1);
    }//GEN-LAST:event_panLLoginMouseDragged

    private void lblLrecuperar_contraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLrecuperar_contraMouseExited
        lblLrecuperar_contra.setText("<HTML>¿Olvidaste tu contraseña?</HTML>");
    }//GEN-LAST:event_lblLrecuperar_contraMouseExited

    private void lblLrecuperar_contraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLrecuperar_contraMouseEntered
        lblLrecuperar_contra.setText("<HTML><U>¿Olvidaste tu contraseña?</U></HTML>");
    }//GEN-LAST:event_lblLrecuperar_contraMouseEntered

    private void lblLminimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLminimizarMouseExited
        lblLminimizar.setIcon((Icon) new ImageIcon(getClass().getResource("../img/LogIn/icons8_minimize_window_24px_1.png")));
    }//GEN-LAST:event_lblLminimizarMouseExited

    private void lblLminimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLminimizarMouseEntered
        lblLminimizar.setIcon((Icon) new ImageIcon(getClass().getResource("../img/LogIn/icons8_minimize_window_24px_4.png")));
    }//GEN-LAST:event_lblLminimizarMouseEntered

    private void lblLminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLminimizarMouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_lblLminimizarMouseClicked

    private void lblLcerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLcerrarMouseExited
        lblLcerrar.setIcon((Icon) new ImageIcon(getClass().getResource("../img/LogIn/icons8_close_window_24px_3.png")));
    }//GEN-LAST:event_lblLcerrarMouseExited

    private void lblLcerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLcerrarMouseEntered
        lblLcerrar.setIcon((Icon) new ImageIcon(getClass().getResource("../img/LogIn/icons8_close_window_24px_6.png")));
    }//GEN-LAST:event_lblLcerrarMouseEntered

    private void lblLcerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLcerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblLcerrarMouseClicked

    /*txtLcorreoKeyTyped allows to log in the system clicking the enter button from psfLcontra password field
      Use global variables: String Lcorreo,Lcontra,Lscontra; Char Lccontra; Int Lpuesto
      Use local variable: Char d */
    private void psfLcontraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_psfLcontraKeyTyped
        char d=evt.getKeyChar();
        if(d == KeyEvent.VK_ENTER)  {
            Acceder();
        }
    }//GEN-LAST:event_psfLcontraKeyTyped

    /*txtLcorreoKeyTyped allows to log in the system clicking the enter button from txtLcorreo text box
      Use global variables: String Lcorreo,Lcontra,Lscontra; Char Lccontra; Int Lpuesto
      Use local variable: Char d */
    private void txtLcorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLcorreoKeyTyped
        char d=evt.getKeyChar();
        if(d == KeyEvent.VK_ENTER)  {
            Acceder();
        }
    }//GEN-LAST:event_txtLcorreoKeyTyped

    private void txtLcorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLcorreoFocusLost
        if(!ALERTA.valmail(txtLcorreo.getText().trim()) && !txtLcorreo.getText().trim().isEmpty())    {
            this.lblLcorreo.setForeground(red);
            this.lblLiusuario.setIcon((Icon) new ImageIcon(getClass().getResource("../img/LogIn/icons8_user_filled_30px_1.png")));
            ALERTA.balloontip(this.txtLcorreo, "Se debe ingresar un correo válido.",30,10).setVisible(true);
        }
        else    {
            if(!Lmail.equals(this.txtLcorreo.getText().trim())) Lcont = 0;
        }
        /*if(ALERTA.valmail(txtLcorreo.getText().trim()) && txtLcorreo.getText().trim().isEmpty())    {
            this.lblLusuario.setForeground(new java.awt.Color(120, 121, 124));
            this.lblLiusuario.setIcon((Icon) new ImageIcon(getClass().getResource("../img/LogIn/icons8_user_filled_30px.png")));
        }*/
    }//GEN-LAST:event_txtLcorreoFocusLost

    /*btnLaccesarActionPerformed allows to log in the system
      Use global variables: String Lcorreo,Lcontra,Lscontra; Char Lccontra; Int Lpuesto
      Doesn't use local variables. */
    private void btnLaccesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaccesarActionPerformed
        Acceder();
    }//GEN-LAST:event_btnLaccesarActionPerformed

    private void lblLrecuperar_contraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLrecuperar_contraMouseClicked
        boolean rep;
        int resp = JOptionPane.showConfirmDialog(null, "¿Olvidaste tu contraseña?", "Recuperar contraseña", 2);
        if (resp==0)  {
            do {
                Lcorreo = JOptionPane.showInputDialog("Escriba su correo.");
                if(!ALERTA.valmail(Lcorreo.trim()) && !Lcorreo.trim().isEmpty())    {
                    rep=true;
                }
                else    {
                    rep=false;
                    Lcodigo = (int)(Math.random() * 99999999 + 10000000);
                    String aa = ALERTA.enviarCorreo(Lcorreo, Lcodigo);  // Return error or null
                    if(aa.equals(""))   {
                        JOptionPane.showMessageDialog(null, "Correo enviado con éxito.", "Envío exitoso", JOptionPane.INFORMATION_MESSAGE);
                        dialogLrecuperar_contrasenha.setVisible(true);
                    }
                    else    {
                        JOptionPane.showMessageDialog(null, "Error al enviar correo. Favor de intentarlo más tarde."/*+aa*/, "Error de correo", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } while (rep);
        }
    }//GEN-LAST:event_lblLrecuperar_contraMouseClicked

    private void dialogLasignar_contrasenhaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dialogLasignar_contrasenhaMousePressed
        if(this.getExtendedState() == this.NORMAL)    {
            X1 = evt.getX();
            Y1 = evt.getY();
        }
    }//GEN-LAST:event_dialogLasignar_contrasenhaMousePressed

    private void dialogLasignar_contrasenhaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dialogLasignar_contrasenhaMouseDragged
        if(this.getExtendedState() == this.NORMAL)    {
            Point mueve = MouseInfo.getPointerInfo().getLocation();
            dialogLasignar_contrasenha.setLocation(mueve.x - X1, mueve.y - Y1);
        }
    }//GEN-LAST:event_dialogLasignar_contrasenhaMouseDragged

    private void txtLcodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLcodigoKeyTyped
        char d=evt.getKeyChar();
        if(d == KeyEvent.VK_ENTER)  {
            confirmarCodigo();
        }
    }//GEN-LAST:event_txtLcodigoKeyTyped

    private void psfLnueva_contraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_psfLnueva_contraKeyTyped
        char d=evt.getKeyChar();
        if(d == KeyEvent.VK_ENTER)  {
            asignarContrasenha();
        }
    }//GEN-LAST:event_psfLnueva_contraKeyTyped

    private void psfLconfirmar_contraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_psfLconfirmar_contraKeyTyped
        char d=evt.getKeyChar();
        if(d == KeyEvent.VK_ENTER)  {
            asignarContrasenha();
        }
    }//GEN-LAST:event_psfLconfirmar_contraKeyTyped

    public void confirmarCodigo()   {
        if(ALERTA.valint(txtLcodigo.getText())) {
            System.out.println("prueba");
            System.out.println(txtLcodigo.getText());
            if(Lcodigo == Integer.parseInt(txtLcodigo.getText().trim()))  {
                dialogLrecuperar_contrasenha.dispose();
                dialogLasignar_contrasenha.setVisible(true);
            }
            else    {
                JOptionPane.showMessageDialog(null,"Revise que el código corresponda con el enviado a su correo.","Código inválido",2);
            }
        }
        else    {
            JOptionPane.showMessageDialog(null,"El código está conformado de 8 dígitos numéricos.","Código inválido",2);
        }
    }
    
    public void asignarContrasenha()    {
        if(psfLnueva_contra.getText().isEmpty())    {
            ALERTA.balloontip(this.psfLnueva_contra,"Este campo no puede quedar vacío.",30,10).setVisible(true);
        }
        if(psfLconfirmar_contra.getText().isEmpty())    {
            ALERTA.balloontip(this.psfLconfirmar_contra,"Vuelva a ingresar la contraseña.",30,10).setVisible(true);
        }
        if(!(psfLconfirmar_contra.getText().isEmpty() && psfLnueva_contra.getText().isEmpty())) {
            if(Arrays.toString(psfLnueva_contra.getPassword()).length() >= 8) {
                if(Arrays.toString(psfLnueva_contra.getPassword()).equals(Arrays.toString(psfLconfirmar_contra.getPassword())))   {
                    Connection con;
                    PreparedStatement ps;
                    try {
                        ConexionMySQL cmysql = new ConexionMySQL();
                        con = (Connection) cmysql.Conectar();
                        ps = con.prepareStatement("UPDATE tbl_empleado SET contrasena = '"+ALERTA.getSHA3(new String(psfLnueva_contra.getPassword()))+"' WHERE correoEmpleado = '"+Lcorreo+"';");
                        int n=ps.executeUpdate();
                        if (n>0)    {
                            JOptionPane.showOptionDialog(this, "Se ha actualizado la contraseña satisfactoriamente.",
                                    "MySQL Information", JOptionPane.INFORMATION_MESSAGE,
                                    JOptionPane.INFORMATION_MESSAGE, null, new Object[]{" 0K "},"0K");
                            this.dialogLasignar_contrasenha.dispose();
                        }
                    }
                    catch(Exception ex) {
                        JOptionPane.showMessageDialog(null,ex);
                    }
                }
                else    {
                    JOptionPane.showMessageDialog(null,"Las contraseñas deben coincidir.","",JOptionPane.WARNING_MESSAGE);
                }
            }
            else    {
                JOptionPane.showMessageDialog(null,"La contraseña debe ser mayor a 8 caracteres.","Contraseña demasiado corta",JOptionPane.WARNING_MESSAGE);
            }
        }
    }
    
    public void LrecuperarContrasena()  {
        this.dialogLasignar_contrasenha.setSize(new Dimension(480, 200));
        this.dialogLasignar_contrasenha.setShape(new RoundRectangle2D.Double(1, 1, 480, 200, 20, 12)); // arriba, costado
        this.dialogLasignar_contrasenha.setLocationRelativeTo(this);
        this.dialogLasignar_contrasenha.setResizable(false);
        this.dialogLasignar_contrasenha.setVisible(true);
    }
    
    private void Acceder()  {
        if(txtLcorreo.getText().trim().isEmpty() && !psfLcontra.getText().trim().isEmpty())    {
            this.lblLcorreo.setForeground(red);
            this.lblLiusuario.setIcon((Icon) new ImageIcon(getClass().getResource("../img/LogIn/icons8_user_filled_30px_1.png")));
            this.lblLcontra.setForeground(new java.awt.Color(120, 121, 124));
            this.lblLipassword.setIcon((Icon) new ImageIcon(getClass().getResource("../img/LogIn/icons8_key_30px.png")));
            JOptionPane.showMessageDialog(null,"El correo no debe quedar vacío.");
        }
        if(psfLcontra.getText().trim().isEmpty() && !txtLcorreo.getText().trim().isEmpty()) {
            Connection con;
            PreparedStatement ps;
            try {
                ConexionMySQL cmysql = new ConexionMySQL();
                con = (Connection) cmysql.Conectar();
                ps = con.prepareStatement("SELECT contrasena FROM tbl_empleado WHERE correoEmpleado = '"+Lcorreo+"' AND estadoActivo = 1;");
                ResultSet rs = ps.executeQuery();
                if(rs.next()==true)    {
                    // Comprueba si tiene contraseña (primer ingreso)
                    if(rs.getString("contrasena")!=null)    {
                        this.lblLcontra.setForeground(red);
                        this.lblLipassword.setIcon((Icon) new ImageIcon(getClass().getResource("../img/LogIn/icons8_key_30px_1.png")));
                        this.lblLcorreo.setForeground(new java.awt.Color(120, 121, 124));
                        this.lblLiusuario.setIcon((Icon) new ImageIcon(getClass().getResource("../img/LogIn/icons8_user_filled_30px.png")));
                        JOptionPane.showMessageDialog(null,"La contraseña no debe quedar vacía.");
                    }
                    if(rs.getString("contrasena")==null)    {
                        JOptionPane.showMessageDialog(null,"Primera vez de ingreso, registre su contraseña","Primer ingreso.",1);
                        LrecuperarContrasena();
                    }
                }
            }
            catch(Exception e)   {
                this.lblLcontra.setForeground(red);
                this.lblLipassword.setIcon((Icon) new ImageIcon(getClass().getResource("../img/LogIn/icons8_key_30px_1.png")));
                this.lblLcorreo.setForeground(new java.awt.Color(120, 121, 124));
                this.lblLiusuario.setIcon((Icon) new ImageIcon(getClass().getResource("../img/LogIn/icons8_user_filled_30px.png")));
                JOptionPane.showMessageDialog(null,"La contraseña no debe quedar vacía.");
            }
        }
        if(txtLcorreo.getText().trim().isEmpty() && psfLcontra.getText().trim().isEmpty()) {
            this.lblLcorreo.setForeground(red);
            this.lblLcontra.setForeground(red);
            this.lblLipassword.setIcon((Icon) new ImageIcon(getClass().getResource("../img/LogIn/icons8_key_30px_1.png")));
            this.lblLiusuario.setIcon((Icon) new ImageIcon(getClass().getResource("../img/LogIn/icons8_user_filled_30px_1.png")));
            JOptionPane.showMessageDialog(null,"El correo y contraseña no deben quedar vacíos.");
        }
        else    {
            this.lblLcorreo.setForeground(new java.awt.Color(120, 121, 124));
            this.lblLcontra.setForeground(new java.awt.Color(120, 121, 124));
            this.lblLipassword.setIcon((Icon) new ImageIcon(getClass().getResource("../img/LogIn/icons8_key_30px.png")));
            this.lblLiusuario.setIcon((Icon) new ImageIcon(getClass().getResource("../img/LogIn/icons8_user_filled_30px.png")));
            Lcorreo = txtLcorreo.getText().trim();

            Connection con;
            PreparedStatement ps, ps2;
            try {
                ConexionMySQL cmysql = new ConexionMySQL();
                con = (Connection) cmysql.Conectar();
                ps = con.prepareStatement("SELECT matricula FROM tbl_empleado WHERE correoEmpleado = '"+Lcorreo+"' AND estadoActivo = 1;");
                ResultSet rs = ps.executeQuery();
                // Comprueba si el correo está registrado
                if(rs.next()!=false)    {
                    ps = con.prepareStatement("SELECT contrasena FROM tbl_empleado WHERE correoEmpleado = '"+Lcorreo+"' AND estadoActivo = 1;");
                    rs = ps.executeQuery();
                    if(rs.next()!=false)    {
                        // Comprueba si tiene contraseña (primer ingreso)
                        if(rs.getString("contrasena")==null)    {
                            JOptionPane.showMessageDialog(null,"Primera vez de ingreso, registre su contraseña","Primer ingreso.",1);
                            LrecuperarContrasena();
                        }
                        else    {
                            ps = con.prepareStatement("SELECT contrasena, puesto, matricula FROM tbl_empleado WHERE correoEmpleado = '"+Lcorreo+"' AND estadoActivo = 1;");
                            rs = ps.executeQuery();
                            // Lee los resultados para autorizar
                            while (rs.next())   {
                                Lpuesto = rs.getInt("puesto");
                                Lcontra = rs.getString("contrasena");
                                Lmatricula = rs.getInt("matricula");
                                Lscontra = ALERTA.getSHA3(new String(psfLcontra.getPassword()));
                                if(Lscontra.equals(Lcontra) && Lpuesto != 3)    {
                                    ps2 = con.prepareStatement("INSERT INTO tbl_bitacoraAccesos(matriculaEmpleado,fecha,ingreso) VALUES ("+Lmatricula+",NOW(),true);");
                                    ps2.executeUpdate();
                                    this.dispose();
                                    MódulosAcceso ma = new MódulosAcceso(Lmatricula);
                                    ma.setVisible(true);
                                    JOptionPane.showMessageDialog(null,"¡Bienvenido a SASERCON!","¡Bienvenido!",1);
                                }
                                else if(Lpuesto == 3)   {
                                    JOptionPane.showMessageDialog(null,"El sistema es para directivos y secretarias.","Acceso denegado.",0);
                                }
                                else    {
                                    JOptionPane.showMessageDialog(null,"Contraseña inválida, favor de verificar.","Contraseña inválida",2);
                                    if(!Lmail.equals(this.txtLcorreo.getText().trim()))   Lmail = this.txtLcorreo.getText().trim();
                                    //Lintentos[Lmatricula] = 
                                    Lcont++;
                                    if(Lcont >= 3)    {
                                        int resp = JOptionPane.showConfirmDialog(null, "¿Olvidaste tu contraseña?", "Recuperar contraseña", 2);
                                        if (resp==0)  {
                                            Lcodigo = (int)(Math.random() * 99999999 + 10000000);
                                            String aa = ALERTA.enviarCorreo(Lcorreo, Lcodigo);
                                            if(aa.equals(""))   {
                                                JOptionPane.showMessageDialog(null, "Correo enviado con éxito.", "Envío exitoso", JOptionPane.INFORMATION_MESSAGE);
                                                dialogLrecuperar_contrasenha.setVisible(true);
                                            }
                                            else    {
                                                JOptionPane.showMessageDialog(null, "Error al enviar correo: "+aa, "Error de correo", JOptionPane.ERROR_MESSAGE);
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                    else    {
                        JOptionPane.showMessageDialog(null,"Error con la Base de Datos.","Error.",2);
                    }
                }
                else    {
                    JOptionPane.showMessageDialog(null,"El correo no está registrado o está dado de baja, favor de verificar o comunicarse a gerencia.","Correo no registrado",2);
                }
                con.close();
            } catch (Exception ex)   {
                JOptionPane.showMessageDialog(null,ex);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaccesar;
    private javax.swing.JButton btnLconfirmar;
    private javax.swing.JButton btnLguardar;
    private javax.swing.JButton btnLregresar;
    private javax.swing.JDialog dialogLasignar_contrasenha;
    private javax.swing.JDialog dialogLrecuperar_contrasenha;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLcerrar;
    private javax.swing.JLabel lblLcerrar1;
    private javax.swing.JLabel lblLcerrar2;
    private javax.swing.JLabel lblLcontra;
    private javax.swing.JLabel lblLcorreo;
    private javax.swing.JLabel lblLipassword;
    private javax.swing.JLabel lblLiusuario;
    private javax.swing.JLabel lblLlogo;
    private javax.swing.JLabel lblLminimizar;
    private javax.swing.JLabel lblLrecuperar_contra;
    private javax.swing.JPanel panLLogin;
    private javax.swing.JPanel panLcontraseña;
    private javax.swing.JPasswordField psfLconfirmar_contra;
    private javax.swing.JPasswordField psfLcontra;
    private javax.swing.JPasswordField psfLnueva_contra;
    private javax.swing.JTextField txtLcodigo;
    private javax.swing.JTextField txtLcorreo;
    // End of variables declaration//GEN-END:variables
}
