/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DMI;

import DMI.ConexionMySQL;
import DMI.Comprobacion;
import static DMI.IngresarEmpleado.c;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.*;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author coner
 */
public class ModificarEmpleado extends javax.swing.JInternalFrame {

public String MEnombre_de_empleado;
public String MEapellido_paterno_empleado;
public String MEapellido_materno_empleado;
public String MEcorreo;
public int MEempresa;
public int MEpuesto;
protected String MEcurp;
protected String MErfc;
protected String MEnss;
public String MEcelular;
public String MEtelefono;
protected String MEtelefono_de_emergencia;
public int MEpais;
public int MEestado;
public int MEciudad;
public int MEalcaldia;
protected String MEnumero_exterior;
protected String MEnumero_interior;
protected String MEcalle;
protected String MEcolonia;
protected int MEcodigo_postal;
protected String MEnombre_del_contacto;
protected String MEapellido_paterno_contacto;
protected String MEapellido_materno_contacto;
protected String MEcorreo_del_contacto;
protected boolean MEvigente;

public int MEtipo;

protected File MEf;
protected FileInputStream MEfoto = null;
protected Image MEfi = null;

static FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "png", "gif", "jpeg");
static Comprobacion c = new Comprobacion();
    /**
     * Creates new form ModificarEmpleado
     */
    public ModificarEmpleado() {
        initComponents();
        this.setIconifiable(true);
        
        ConexionMySQL cmysql = new ConexionMySQL();
        Connection conec = (Connection) cmysql.Conectar();
        
        try {
            Statement st=conec.createStatement();
            ResultSet rs = st.executeQuery("SELECT pais FROM pais");
            while (rs.next())   {
                this.cboxMEpais.addItem(rs.getString("pais"));
            }
        } catch(Exception ex)   {
            JOptionPane.showMessageDialog(null,ex,"SQL error",2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMEregresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtMEnombre_de_empleado = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtMEcorreo = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        cboxMEempresa = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        txtMEcurp = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtMErfc = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtMEnss = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtMEcelular = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtMEtelefono = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtMEtelefono_de_emergencia = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtMEnombre_del_contacto = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtMEcorreo_del_contacto = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        lblMEno_vigente = new javax.swing.JLabel();
        tgbMEvigente = new javax.swing.JToggleButton();
        lblMEvigente = new javax.swing.JLabel();
        btnMEguardar = new javax.swing.JButton();
        btnMEcancelar = new javax.swing.JButton();
        btnMEfoto = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        txtMEapellido_paterno_empleado = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtMEapellido_materno_empleado = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtMEapellido_paterno_contacto = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txtMEapellido_materno_contacto = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        cboxMEpuesto = new javax.swing.JComboBox<>();
        jLabel45 = new javax.swing.JLabel();
        cboxMEpais = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        cboxMEestado = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        txtMEnumero_exterior = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtMEnumero_interior = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txtMEcalle = new javax.swing.JTextField();
        txtMEcolonia = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        txtMEcodigo_postal = new javax.swing.JTextField();
        cboxMEciudad = new javax.swing.JComboBox<>();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        cboxMEalcaldia = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();

        btnMEregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_arrow_back_grey600_18dp.png"))); // NOI18N
        btnMEregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMEregresarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar empleado"));

        jLabel23.setText("Nombre:");

        jLabel24.setText("Correo:");

        jLabel25.setText("Empresa:");

        cboxMEempresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Empresa", "SERCON", "ICC", "SAMSARA", "MABA" }));

        jLabel27.setText("CURP:");

        jLabel28.setText("RFC:");

        jLabel29.setText("Número de Seguro Social:");

        jLabel30.setText("Teléfono celular:");

        jLabel31.setText("Teléfono:");

        txtMEtelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMEtelefonoActionPerformed(evt);
            }
        });

        jLabel32.setText("Teléfono emergencia:");

        jLabel33.setText("Nombre:");

        jLabel34.setText("Correo de contacto:");

        jLabel35.setText("Status:");

        lblMEno_vigente.setText("No vigente");

        tgbMEvigente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_check_box_grey600_18dp.png"))); // NOI18N
        tgbMEvigente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgbMEvigenteActionPerformed(evt);
            }
        });

        lblMEvigente.setText("Vigente");

        btnMEguardar.setText("Guardar");
        btnMEguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMEguardarActionPerformed(evt);
            }
        });

        btnMEcancelar.setText("Cancelar");
        btnMEcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMEcancelarActionPerformed(evt);
            }
        });

        btnMEfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_assignment_ind_grey600_36dp.png"))); // NOI18N
        btnMEfoto.setText("Foto");
        btnMEfoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMEfoto.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMEfoto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMEfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMEfotoActionPerformed(evt);
            }
        });

        jLabel36.setText("Apellido Paterno:");

        jLabel37.setText("Apellido Materno:");

        jLabel38.setText("Apellido Paterno:");

        txtMEapellido_paterno_contacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMEapellido_paterno_contactoActionPerformed(evt);
            }
        });

        jLabel39.setText("Apellido Materno:");

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel43.setText("Datos del empleado");

        jLabel44.setText("Puesto:");

        cboxMEpuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Puesto", "Directivo", "Secretaria", "Técnico" }));
        cboxMEpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxMEpuestoActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel45.setText("Dirección del empleado");

        cboxMEpais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un país" }));
        cboxMEpais.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxMEpaisItemStateChanged(evt);
            }
        });
        cboxMEpais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxMEpaisActionPerformed(evt);
            }
        });

        jLabel26.setText("País:");

        jLabel40.setText("Estado:");

        cboxMEestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un estado" }));
        cboxMEestado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxMEestadoItemStateChanged(evt);
            }
        });

        jLabel41.setText("Número exterior:");

        txtMEnumero_exterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMEnumero_exteriorActionPerformed(evt);
            }
        });

        jLabel42.setText("Número interior:");

        jLabel46.setText("Calle:");

        txtMEcalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMEcalleActionPerformed(evt);
            }
        });

        jLabel47.setText("Colonia:");

        jLabel48.setText("Código Postal:");

        cboxMEciudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la ciudad" }));

        jLabel49.setText("Ciudad:");

        jLabel50.setText("Alcaldía:");

        cboxMEalcaldia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la alcaldía" }));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Contacto del empleado");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMEnombre_del_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMEapellido_paterno_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMEapellido_materno_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel49, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel50, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cboxMEciudad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboxMEestado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboxMEpais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboxMEalcaldia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(102, 102, 102)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel47, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMEcodigo_postal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtMEcolonia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addComponent(txtMEnumero_interior, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMEcalle, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMEnumero_exterior, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMEcorreo_del_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMEnss, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(128, 128, 128)
                                    .addComponent(tgbMEvigente, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblMEvigente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMEcancelar)
                                    .addGap(29, 29, 29)
                                    .addComponent(btnMEguardar))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                .addComponent(jLabel19)
                                                .addComponent(jLabel45)
                                                .addComponent(jLabel43))
                                            .addGap(107, 107, 107))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel23)
                                                        .addComponent(jLabel24))
                                                    .addGap(10, 10, 10)
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtMEcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtMEnombre_de_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(jLabel28)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtMErfc, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtMEcurp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                    .addComponent(jLabel37)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtMEapellido_materno_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                    .addComponent(jLabel36)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtMEapellido_paterno_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel25)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cboxMEempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel44)
                                                .addGap(18, 18, 18)
                                                .addComponent(cboxMEpuesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLabel27)))
                                    .addGap(18, 18, 18)
                                    .addComponent(btnMEfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(33, 33, 33)
                        .addComponent(lblMEno_vigente))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMEcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMEtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMEtelefono_de_emergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(txtMEnombre_de_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMEcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25)
                                    .addComponent(cboxMEempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel44)
                                    .addComponent(cboxMEpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27)
                                    .addComponent(txtMEcurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel36)
                                    .addComponent(txtMEapellido_paterno_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel37)
                                    .addComponent(txtMEapellido_materno_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMErfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)))
                    .addComponent(btnMEfoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtMEnss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtMEcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtMEtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txtMEtelefono_de_emergencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel45)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(cboxMEpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(txtMEnumero_exterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(cboxMEestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42)
                    .addComponent(txtMEnumero_interior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(cboxMEciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46)
                    .addComponent(txtMEcalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(cboxMEalcaldia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47)
                    .addComponent(txtMEcolonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(txtMEcodigo_postal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txtMEnombre_del_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38)
                    .addComponent(txtMEapellido_paterno_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(txtMEapellido_materno_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtMEcorreo_del_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel35)
                                .addComponent(lblMEno_vigente))
                            .addComponent(tgbMEvigente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnMEcancelar)
                                .addComponent(btnMEguardar))
                            .addGap(1, 1, 1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblMEvigente)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMEregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMEregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(463, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMEregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMEregresarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnMEregresarActionPerformed

    private void txtMEtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMEtelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMEtelefonoActionPerformed

    private void tgbMEvigenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgbMEvigenteActionPerformed
        if(tgbMEvigente.isSelected())   {
            tgbMEvigente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_check_box_black_18dp.png")));
        }
        else    {
            tgbMEvigente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_check_box_outline_blank_black_18dp.png")));
        }
    }//GEN-LAST:event_tgbMEvigenteActionPerformed

    private void btnMEguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMEguardarActionPerformed
        MEnombre_de_empleado = this.txtMEnombre_de_empleado.getText().trim();
        MEapellido_paterno_empleado = this.txtMEapellido_paterno_empleado.getText().trim();
        MEapellido_materno_empleado = this.txtMEapellido_materno_empleado.getText().trim();
        MEcorreo = this.txtMEcorreo.getText().trim();
        MEempresa = this.cboxMEempresa.getSelectedIndex();
        MEpuesto = this.cboxMEempresa.getSelectedIndex();
        MEcurp = this.txtMEcurp.getText().trim();
        MEnss = this.txtMEnss.getText().trim();
        MEcelular = this.txtMEcelular.getText().trim();
        MEtelefono_de_emergencia = this.txtMEtelefono_de_emergencia.getText().trim();
        MEnombre_del_contacto = this.txtMEnombre_del_contacto.getText().trim();
        MEapellido_paterno_contacto = this.txtMEapellido_paterno_contacto.getText().trim();
        MEapellido_materno_contacto = this.txtMEapellido_materno_contacto.getText().trim();
        MEcorreo_del_contacto = this.txtMEcorreo_del_contacto.getText().trim();
        MEvigente = this.tgbMEvigente.isSelected();
        MEtelefono = this.txtMEtelefono.getText().trim();
        MErfc = this.txtMErfc.getText().trim();
        
        MEnumero_exterior = this.txtMEnumero_exterior.getText().trim();
        MEnumero_interior = this.txtMEnumero_interior.getText().trim();
        MEcalle = this.txtMEcalle.getText().trim();
        MEcolonia = this.txtMEcolonia.getText().trim();
        MEcodigo_postal = Integer.parseInt(this.txtMEcodigo_postal.getText().trim());
        MEtipo = 4;
        MEalcaldia = this.cboxMEalcaldia.getSelectedIndex();
        
        
        if(c.valtext(MEnombre_de_empleado)&&c.valtext(MEapellido_paterno_empleado)&&c.valtext(MEapellido_materno_empleado)&&
                c.valmail(MEcorreo)&&MEempresa!=0&&MEpuesto!=0&&c.valcurp(MEcurp)&&c.valnss(MEnss)&&c.valcel(MEcelular)&&
                c.valtel(MEtelefono_de_emergencia)&&c.valtext(MEnombre_del_contacto)&&c.valtext(MEapellido_paterno_contacto)&&
                c.valtext(MEapellido_materno_contacto)&&c.valmail(MEcorreo_del_contacto)&&c.valtel(MEtelefono)&&
                c.valrfc(MErfc)&&c.valne(MEnumero_exterior)&&c.valni(MEnumero_interior)&&c.vacio(MEcalle)&&
                c.valtext(MEcolonia)&&c.valcp(this.txtMEcodigo_postal.getText().trim())&&MEalcaldia!=0)    {
            
            actualizar();
        }
        else    {
            JOptionPane.showMessageDialog(null, "El formato de los campos es incorrecto. Revise de nuevo.", "Datos incorrectos", 2);
        }
    }//GEN-LAST:event_btnMEguardarActionPerformed

    private void btnMEcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMEcancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnMEcancelarActionPerformed

    private void btnMEfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMEfotoActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(filter);
        chooser.showOpenDialog(null);
        MEf = chooser.getSelectedFile();
        try {
            MEfoto = new FileInputStream(MEf);
            MEfi=Toolkit.getDefaultToolkit().createImage(MEf.getAbsolutePath());
            MEfi=MEfi.getScaledInstance(144, 144, 1);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(IngresarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMEfotoActionPerformed

    private void txtMEapellido_paterno_contactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMEapellido_paterno_contactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMEapellido_paterno_contactoActionPerformed

    private void cboxMEpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxMEpuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxMEpuestoActionPerformed

    private void txtMEnumero_exteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMEnumero_exteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMEnumero_exteriorActionPerformed

    private void txtMEcalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMEcalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMEcalleActionPerformed

    private void cboxMEpaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxMEpaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxMEpaisActionPerformed

    private void cboxMEpaisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxMEpaisItemStateChanged
        this.cboxMEestado.removeAllItems();
        this.cboxMEestado.addItem("Seleccione un estado");
        ConexionMySQL cmysql = new ConexionMySQL();
        Connection conec = (Connection) cmysql.Conectar();
        
        try {
            Statement st=conec.createStatement();
            ResultSet rs = st.executeQuery("SELECT estado FROM estado WHERE clavePais = "+cboxMEpais.getSelectedIndex());
            while (rs.next())   {
                this.cboxMEestado.addItem(rs.getString("estado"));
            }
        } catch(Exception ex)   {
            JOptionPane.showMessageDialog(null,ex,"SQL error",2);
        }
    }//GEN-LAST:event_cboxMEpaisItemStateChanged

    private void cboxMEestadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxMEestadoItemStateChanged
        this.cboxMEalcaldia.removeAllItems();
        this.cboxMEalcaldia.addItem("Seleccione la alcaldía");
        ConexionMySQL cmysql = new ConexionMySQL();
        Connection conec = (Connection) cmysql.Conectar();
        
        try {
            Statement st=conec.createStatement();
            ResultSet rs = st.executeQuery("SELECT alcaldia FROM alcaldia WHERE claveCiudad = "+cboxMEestado.getSelectedIndex());
            while (rs.next())   {
                this.cboxMEalcaldia.addItem(rs.getString("alcaldia"));
            }
        } catch(Exception ex)   {
            JOptionPane.showMessageDialog(null,ex,"SQL error",2);
        }
    }//GEN-LAST:event_cboxMEestadoItemStateChanged
    
    
//    //metodo para editar datos
//    String id_actual="";
//    void EditarDatos(String ids)
//    {
//       
//        String senSQL="";
//        String id_e="";
//        String nom="";
//        String dir="";
//        String email="";
//        
//       
//        
//        ConexionMySQL cmysql=new ConexionMySQL();
//        Connection conec=cmysql.Conectar();
//        
//        senSQL="SELECT Nombre, Direccion, Email FROM agenda "
//                + " WHERE Nombre='"+ids+"'";
//        try{
//            Statement st=conec.createStatement();
//            ResultSet rs=st.executeQuery(senSQL);
//            
//            while(rs.next()){
//                //id_e=rs.getString("id");
//                nom=rs.getString("Nombre");
//                dir=rs.getString("Direccion");
//               email=rs.getString("Email");
//                
//                
//            }
//            this.txtNom_up.setText(nom);
//            this.txtDir_up.setText(dir);
//            this.txtEmail_up.setText(email);
//            
//            id_actual=ids;
//        }catch(SQLException ex){
//                JOptionPane.showMessageDialog(null,ex);
//        }
//    }

    
    public void actualizar()  {
        ConexionMySQL cmysql = new ConexionMySQL();
        Connection conec = (Connection) cmysql.Conectar();
        
        String senSQL = "UPDATE empleado SET nombreEmpleado = ?, apellidoPaternoEmpleado = ?, apellidoMaternoEmpleado = ?,"+
                "correoEmpleado = ?, empresa = ?, puesto = ?, curp = ?, numeroSeguroSocial = ?, celular = ?,"+
                "telefonoEmergencia = ?, nombreContacto = ?, apellidoPaternoContacto = ?, apellidoMaternoContacto = ?,"+
                "correoContacto = ?, estadoActivo = ?, telefono = ?, fotoEmpleado = ?, RFC = ? WHERE matricula = ";//+indice;
        String senSQL2 = "UPDATE direccion SET numeroExterior = ?, numeroInterior = ?, calle = ?, colonia = ?, "+
                "codigoPostal = ?, tipo = ?, alcaldia = ?"+
                "WHERE direccion.clave = direccionEmpleado.direccion AND direccionEmpleado.claveEmpleado = empleado.matricula AND empleado.matricula = ";//+MEindice;

        try {
            PreparedStatement ps = conec.prepareStatement(senSQL);
            ps.setString(1,MEnombre_de_empleado);
            ps.setString(2,MEapellido_paterno_empleado);
            ps.setString(3,MEapellido_materno_empleado);
            ps.setString(4,MEcorreo);
            ps.setInt(5,MEempresa);
            ps.setInt(6,MEpuesto);
            ps.setString(7,MEcurp);
            ps.setString(8,MEnss);
            ps.setString(9,MEcelular);
            ps.setString(10,MEtelefono_de_emergencia);
            ps.setString(11,MEnombre_del_contacto);
            ps.setString(12,MEapellido_paterno_contacto);
            ps.setString(13,MEapellido_materno_contacto);
            ps.setString(14,MEcorreo_del_contacto);
            ps.setBoolean(15,MEvigente);
            ps.setString(16,MEtelefono);
            ps.setBinaryStream(17,MEfoto);
            ps.setString(18,MErfc);
            PreparedStatement ps2 = conec.prepareStatement(senSQL2);
            ps.setString(1,MEnumero_exterior);
            ps.setString(2,MEnumero_interior);
            ps.setString(3,MEcalle);
            ps.setString(4,MEcolonia);
            ps.setInt(5,MEcodigo_postal);
            ps.setInt(6,MEtipo);
            ps.setInt(7,MEalcaldia);
            int n = ps.executeUpdate();
            int m = ps2.executeUpdate();
            if (n > 0 && m > 0)  {
                JOptionPane.showOptionDialog(this, "Se han actualizado los datos satisfactoriamente",
                        "MySQL Information", JOptionPane.INFORMATION_MESSAGE,
                        JOptionPane.INFORMATION_MESSAGE, null, new Object[]{" 0K "},"0K");
                this.dispose();
            }
        }
        catch( SQLException ex )    {
            JOptionPane.showMessageDialog(null,ex);
        }
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMEcancelar;
    private javax.swing.JButton btnMEfoto;
    private javax.swing.JButton btnMEguardar;
    private javax.swing.JButton btnMEregresar;
    private javax.swing.JComboBox<String> cboxMEalcaldia;
    private javax.swing.JComboBox<String> cboxMEciudad;
    private javax.swing.JComboBox<String> cboxMEempresa;
    private javax.swing.JComboBox<String> cboxMEestado;
    private javax.swing.JComboBox<String> cboxMEpais;
    private javax.swing.JComboBox<String> cboxMEpuesto;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMEno_vigente;
    private javax.swing.JLabel lblMEvigente;
    private javax.swing.JToggleButton tgbMEvigente;
    private javax.swing.JTextField txtMEapellido_materno_contacto;
    private javax.swing.JTextField txtMEapellido_materno_empleado;
    private javax.swing.JTextField txtMEapellido_paterno_contacto;
    private javax.swing.JTextField txtMEapellido_paterno_empleado;
    private javax.swing.JTextField txtMEcalle;
    private javax.swing.JTextField txtMEcelular;
    private javax.swing.JTextField txtMEcodigo_postal;
    private javax.swing.JTextField txtMEcolonia;
    private javax.swing.JTextField txtMEcorreo;
    private javax.swing.JTextField txtMEcorreo_del_contacto;
    private javax.swing.JTextField txtMEcurp;
    private javax.swing.JTextField txtMEnombre_de_empleado;
    private javax.swing.JTextField txtMEnombre_del_contacto;
    private javax.swing.JTextField txtMEnss;
    private javax.swing.JTextField txtMEnumero_exterior;
    private javax.swing.JTextField txtMEnumero_interior;
    private javax.swing.JTextField txtMErfc;
    private javax.swing.JTextField txtMEtelefono;
    private javax.swing.JTextField txtMEtelefono_de_emergencia;
    // End of variables declaration//GEN-END:variables
}
