/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sercon.sasercon;

import java.awt.*;
import java.io.*;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author coner
 */
public class IngresarEmpleado extends javax.swing.JInternalFrame {

public String IEnombre_de_empleado;
public String IEapellido_paterno_empleado;
public String IEapellido_materno_empleado;
public String IEcorreo;
public int IEpuesto;
protected String IEcurp;
protected String IErfc;
protected String IEnss;
public String IEcelular;
public String IEtelefono;
protected String IEtelefono_emergencia;
public int IEpais;
public int IEestado;
public int IEciudad;
public int IEalcaldia;
protected String IEnumero_exterior;
protected String IEnumero_interior;
protected String IEcalle;
protected String IEcolonia;
protected int IEcodigo_postal;
protected String IEnombre_contacto;
protected String IEapellido_paterno_contacto;
protected String IEapellido_materno_contacto;
protected String IEcorreo_contacto;
protected boolean IEvigente;
protected boolean IEn = false, IEap = false, IEam = false, IEfn = false;
protected int IEmatricula;
protected Date IEfecha_nacimiento = new Date();

public int IEtipo;

protected File IEf;
protected FileInputStream IEfoto = null;
protected Image IEfi = null;

static FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "png", "gif", "jpeg");
static Comprobacion ALERTA = new Comprobacion();

public DateFormat ffecha = new SimpleDateFormat("yyyy/MM/dd");
/**
     * Creates new form IngresarEmpleado
     */
    public IngresarEmpleado() {
        initComponents();
        try {
            //System.out.println(ffecha.format(this.dcIEfecha_nacimiento.getDate()));
            this.dcIEfecha_nacimiento.setMinSelectableDate(ffecha.parse("1910/11/29"));
            this.dcIEfecha_nacimiento.setMaxSelectableDate(ffecha.parse("2001/11/29"));
        } catch (Exception e)	{
            JOptionPane.showMessageDialog(null, "El valor que usted ingresó no es una fecha", "Fecha no ingresada.", 0);
            //e.printStackTrace();
        }
        
        try {
            ConexionMySQL cmysql = new ConexionMySQL();
            Connection conec = (Connection) cmysql.Conectar();
            Statement st=conec.createStatement();
            ResultSet rs = st.executeQuery("SELECT pais FROM tbl_pais;");
            while (rs.next())   {
                this.cboxIEpais.addItem(rs.getString("pais"));
            }
        } catch(Exception ex)   {
            JOptionPane.showMessageDialog(null,ex,"SQL error",2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtIEnombre_de_empleado = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtIEcorreo = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtIEcurp = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtIErfc = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtIEnss = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtIEtelefono_emergencia = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtIEtelefono = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtIEcelular = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtIEnombre_contacto = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtIEcorreo_contacto = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        lblIEno_vigente = new javax.swing.JLabel();
        tgbIEvigente = new javax.swing.JToggleButton();
        lblIEvigente = new javax.swing.JLabel();
        btnIEguardar = new javax.swing.JButton();
        btnIEcancelar = new javax.swing.JButton();
        btnIEfoto = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        txtIEapellido_paterno_empleado = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtIEapellido_materno_empleado = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtIEapellido_paterno_contacto = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txtIEapellido_materno_contacto = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        cboxIEpuesto = new javax.swing.JComboBox<>();
        jLabel45 = new javax.swing.JLabel();
        cboxIEpais = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        cboxIEestado = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        txtIEnumero_exterior = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtIEnumero_interior = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txtIEcalle = new javax.swing.JTextField();
        txtIEcolonia = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        txtIEcodigo_postal = new javax.swing.JTextField();
        cboxIEciudad = new javax.swing.JComboBox<>();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        cboxIEalcaldia = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        dcIEfecha_nacimiento = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Nuevo Empleado");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Nuevo Empleado"));

        jLabel23.setText("Nombre:");

        txtIEnombre_de_empleado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIEnombre_de_empleadoFocusLost(evt);
            }
        });

        jLabel24.setText("Correo:");

        jLabel27.setText("CURP:");

        txtIEcurp.setEditable(false);
        txtIEcurp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIEcurpMouseClicked(evt);
            }
        });

        jLabel28.setText("RFC:");

        txtIErfc.setEditable(false);
        txtIErfc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIErfcMouseClicked(evt);
            }
        });

        jLabel29.setText("Número de Seguro Social:");

        jLabel30.setText("Teléfono emergencia:");

        jLabel31.setText("Teléfono:");

        txtIEtelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIEtelefonoActionPerformed(evt);
            }
        });

        jLabel32.setText("Teléfono celular:");

        jLabel33.setText("Nombre:");

        jLabel34.setText("Correo de contacto:");

        jLabel35.setText("Status:");

        lblIEno_vigente.setText("No vigente");

        tgbIEvigente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_check_box_black_18dp.png"))); // NOI18N
        tgbIEvigente.setSelected(true);
        tgbIEvigente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgbIEvigenteActionPerformed(evt);
            }
        });

        lblIEvigente.setText("Vigente");

        btnIEguardar.setText("Guardar");
        btnIEguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIEguardarActionPerformed(evt);
            }
        });

        btnIEcancelar.setText("Cancelar");
        btnIEcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIEcancelarActionPerformed(evt);
            }
        });

        btnIEfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MódulosAcceso/Módulos/add_photo.png"))); // NOI18N
        btnIEfoto.setText("Foto");
        btnIEfoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIEfoto.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnIEfoto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIEfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIEfotoActionPerformed(evt);
            }
        });

        jLabel36.setText("Apellido Paterno:");

        txtIEapellido_paterno_empleado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIEapellido_paterno_empleadoFocusLost(evt);
            }
        });

        jLabel37.setText("Apellido Materno:");

        txtIEapellido_materno_empleado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIEapellido_materno_empleadoFocusLost(evt);
            }
        });

        jLabel38.setText("Apellido Paterno:");

        txtIEapellido_paterno_contacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIEapellido_paterno_contactoActionPerformed(evt);
            }
        });

        jLabel39.setText("Apellido Materno:");

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel43.setText("Datos del empleado");

        jLabel44.setText("Puesto:");

        cboxIEpuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Puesto", "Directivo", "Secretaria", "Técnico" }));
        cboxIEpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxIEpuestoActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel45.setText("Dirección del empleado");

        cboxIEpais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un país" }));
        cboxIEpais.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxIEpaisItemStateChanged(evt);
            }
        });
        cboxIEpais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxIEpaisActionPerformed(evt);
            }
        });

        jLabel26.setText("País:");

        jLabel40.setText("Estado:");

        cboxIEestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un estado" }));
        cboxIEestado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxIEestadoItemStateChanged(evt);
            }
        });

        jLabel41.setText("Número exterior:");

        jLabel42.setText("Número interior:");

        jLabel46.setText("Calle:");

        jLabel47.setText("Colonia:");

        jLabel48.setText("Código Postal:");

        cboxIEciudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la ciudad" }));

        jLabel49.setText("Ciudad:");

        jLabel50.setText("Alcaldía:");

        cboxIEalcaldia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la alcaldía" }));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Contacto del empleado");

        jLabel1.setText("Nacimiento:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIEnombre_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIEapellido_paterno_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIEapellido_materno_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel49, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel50, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cboxIEciudad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboxIEestado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboxIEpais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboxIEalcaldia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(102, 102, 102)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel47, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtIEcodigo_postal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtIEnumero_interior, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIEcalle, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIEcolonia, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIEnumero_exterior)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIEcorreo_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIEnss)
                                .addGap(425, 425, 425))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(tgbIEvigente, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblIEvigente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIEcancelar)
                                .addGap(29, 29, 29)
                                .addComponent(btnIEguardar))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(220, 220, 220)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel45)
                                            .addComponent(jLabel43))
                                        .addGap(125, 125, 125))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel27)
                                                            .addComponent(jLabel28))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtIErfc, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txtIEcurp, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addComponent(jLabel1)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(dcIEfecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(143, 143, 143)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtIEtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtIEtelefono_emergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtIEcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel23)
                                                    .addComponent(jLabel24))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addComponent(txtIEnombre_de_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addComponent(txtIEcorreo)
                                                        .addGap(46, 46, 46)))
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                        .addComponent(jLabel36)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtIEapellido_paterno_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel30)
                                                            .addComponent(jLabel37)
                                                            .addComponent(jLabel31)
                                                            .addComponent(jLabel32)
                                                            .addComponent(jLabel44))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtIEapellido_materno_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(cboxIEpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                        .addGap(18, 18, 18)))
                                .addComponent(btnIEfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(33, 33, 33)
                        .addComponent(lblIEno_vigente))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIEfoto)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel23)
                                            .addComponent(txtIEnombre_de_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtIEcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel24)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel36)
                                            .addComponent(txtIEapellido_paterno_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel37)
                                            .addComponent(txtIEapellido_materno_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel30)
                                            .addComponent(txtIEtelefono_emergencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(dcIEfecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel31)
                                    .addComponent(txtIEtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel32)
                                    .addComponent(txtIEcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIEcurp))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIErfc))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(txtIEnss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxIEpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel45)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(cboxIEpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(txtIEnumero_exterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(cboxIEestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42)
                    .addComponent(txtIEnumero_interior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(cboxIEciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46)
                    .addComponent(txtIEcalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(cboxIEalcaldia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47)
                    .addComponent(txtIEcolonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(txtIEcodigo_postal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txtIEnombre_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38)
                    .addComponent(txtIEapellido_paterno_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(txtIEapellido_materno_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtIEcorreo_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel35)
                                .addComponent(lblIEno_vigente))
                            .addComponent(tgbIEvigente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnIEcancelar)
                                .addComponent(btnIEguardar))
                            .addGap(1, 1, 1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblIEvigente)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jScrollPane.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    * Inserts into database all employeer data
    */
    public void ingresar()  {
        
        try {
            ConexionMySQL cmysql = new ConexionMySQL();
            Connection conec = (Connection) cmysql.Conectar();

            String senSQL = "INSERT INTO tbl_empleado (nombreEmpleado,apellidoPaternoEmpleado,apellidoMaternoEmpleado,fechaNacimiento,correoEmpleado,puesto,curp,numeroSeguroSocial,celular,telefonoEmergencia,nombreContacto,apellidoPaternoContacto,apellidoMaternoContacto,correoContacto,estadoActivo,telefono,fotoEmpleado,RFC) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            String senSQL2 = "INSERT INTO tbl_direccion (numeroExterior,numeroInterior,calle,colonia,codigoPostal,tipo,alcaldia) VALUES(?,?,?,?,?,?,?)";
            
            java.util.Date d = this.dcIEfecha_nacimiento.getDate();
            java.sql.Date sqldate = new java.sql.Date(d.getTime());
            
            PreparedStatement ps = conec.prepareStatement(senSQL);
            ps.setString(1,ALERTA.getEncrypted(IEnombre_de_empleado));
            ps.setString(2,ALERTA.getEncrypted(IEapellido_paterno_empleado));
            ps.setString(3,ALERTA.getEncrypted(IEapellido_materno_empleado));
            ps.setDate(4,sqldate);
            ps.setString(5,ALERTA.getEncrypted(IEcorreo));
            ps.setInt(6,IEpuesto);
            ps.setString(7,ALERTA.getEncrypted(IEcurp));
            ps.setString(8,ALERTA.getEncrypted(IEnss));
            ps.setString(9,ALERTA.getEncrypted(IEcelular));
            ps.setString(10,ALERTA.getEncrypted(IEtelefono_emergencia));
            ps.setString(11,ALERTA.getEncrypted(IEnombre_contacto));
            ps.setString(12,ALERTA.getEncrypted(IEapellido_paterno_contacto));
            ps.setString(13,ALERTA.getEncrypted(IEapellido_materno_contacto));
            ps.setString(14,IEcorreo_contacto);
            ps.setBoolean(15,IEvigente);
            ps.setString(16,ALERTA.getEncrypted(IEtelefono));
            ps.setBinaryStream(17,IEfoto);
            ps.setString(18,ALERTA.getEncrypted(IErfc));
            
            PreparedStatement ps2 = conec.prepareStatement(senSQL2);
            ps2.setString(1,IEnumero_exterior);
            ps2.setString(2,IEnumero_interior);
            ps2.setString(3,IEcalle);
            ps2.setString(4,IEcolonia);
            ps2.setInt(5,IEcodigo_postal);
            ps2.setInt(6,IEtipo);
            ps2.setInt(7,IEalcaldia);
            
            PreparedStatement ps3 = conec.prepareStatement("INSERT INTO tbl_direccionEmpleado VALUES((SELECT MAX(matricula) FROM tbl_empleado),(SELECT MAX(clave) FROM tbl_direccion))");
            int m = ps2.executeUpdate();
            int n = ps.executeUpdate();
            int o = ps3.executeUpdate();
            Statement st = conec.createStatement();
            ResultSet rs = st.executeQuery("SELECT MAX(matricula) FROM tbl_empleado");
            while(rs.next()) {
                IEmatricula = rs.getInt("MAX(matricula)");
            }
            if (n > 0 && m > 0 && o > 0)  {
                JOptionPane.showOptionDialog(this, "Se han guardado sus datos satisfactoriamente.",
                        "MySQL Information", JOptionPane.INFORMATION_MESSAGE,
                        JOptionPane.INFORMATION_MESSAGE, null, new Object[]{" 0K "},"0K");
                this.dispose();
            }
        }
        catch( SQLException ex )    {
            JOptionPane.showMessageDialog(null,ex,"SQL error",2);
        }
    }

    
    private void btnIEfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIEfotoActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(filter);
        chooser.showOpenDialog(null);
        IEf = chooser.getSelectedFile();
        try {
            IEfoto = new FileInputStream(IEf);
            IEfi=Toolkit.getDefaultToolkit().createImage(IEf.getAbsolutePath());
            IEfi=IEfi.getScaledInstance(144, 144, 1);
            btnIEfoto.setIcon(new ImageIcon(IEfi));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(IngresarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIEfotoActionPerformed

    private void btnIEcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIEcancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnIEcancelarActionPerformed

    private void btnIEguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIEguardarActionPerformed
        IEnombre_de_empleado = this.txtIEnombre_de_empleado.getText().trim();
        IEapellido_paterno_empleado = this.txtIEapellido_paterno_empleado.getText().trim();
        IEapellido_materno_empleado = this.txtIEapellido_materno_empleado.getText().trim();
        IEfecha_nacimiento = this.dcIEfecha_nacimiento.getDate();
        IEcorreo = this.txtIEcorreo.getText().trim();
        IEcurp = this.txtIEcurp.getText();
        IEnss = this.txtIEnss.getText().trim();
        IEtelefono = this.txtIEtelefono.getText().trim();
        IEtelefono_emergencia = this.txtIEtelefono_emergencia.getText().trim();
        IEcelular = this.txtIEcelular.getText().trim();
        IEnombre_contacto = this.txtIEnombre_contacto.getText().trim();
        IEapellido_paterno_contacto = this.txtIEapellido_paterno_contacto.getText().trim();
        IEapellido_materno_contacto = this.txtIEapellido_materno_contacto.getText().trim();
        IEcorreo_contacto = this.txtIEcorreo_contacto.getText().trim();
        IEpuesto = this.cboxIEpuesto.getSelectedIndex();
        IEvigente = this.tgbIEvigente.isSelected();
        IErfc = this.txtIErfc.getText();
        
        IEnumero_exterior = this.txtIEnumero_exterior.getText().trim();
        IEnumero_interior = this.txtIEnumero_interior.getText().trim();
        IEcalle = this.txtIEcalle.getText().trim();
        IEcolonia = this.txtIEcolonia.getText().trim();
        IEcodigo_postal = Integer.parseInt(this.txtIEcodigo_postal.getText().trim());
        IEtipo = 4;
        IEalcaldia = this.cboxIEalcaldia.getSelectedIndex();
        
        String pr="";
        
        if(ALERTA.valtext(IEnombre_de_empleado)&&ALERTA.valtext(IEapellido_paterno_empleado)&&ALERTA.valtext(IEapellido_materno_empleado)&&
                ALERTA.valmail(IEcorreo)&&IEpuesto!=0&&ALERTA.valcurp(IEcurp)&&ALERTA.valnss(IEnss)&&ALERTA.valcel(IEcelular)&&
                ALERTA.valtel(IEtelefono_emergencia)&&ALERTA.valtext(IEnombre_contacto)&&ALERTA.valtext(IEapellido_paterno_contacto)&&
                ALERTA.valtext(IEapellido_materno_contacto)&&ALERTA.valmail(IEcorreo_contacto)&&ALERTA.valtel(IEtelefono)&&
                ALERTA.valrfc(IErfc)&&ALERTA.valne(IEnumero_exterior)&&ALERTA.valni(IEnumero_interior)&&!ALERTA.vacio(IEcalle)&&
                ALERTA.valtext(IEcolonia)&&ALERTA.valcp(this.txtIEcodigo_postal.getText().trim())&&IEalcaldia!=0)    {
            ingresar();
        }
        if(!ALERTA.valtext(IEnombre_de_empleado)) {
            pr=pr+"\nNombre del empleado";
        }
        if(!ALERTA.valtext(IEapellido_paterno_empleado))    {
            pr=pr+"\nApellido paterno del empleado";
        }
        if(!ALERTA.valtext(IEapellido_materno_empleado))    {
            pr=pr+"\nApellido materno del empleado";
        }
        if(!ALERTA.valmail(IEcorreo))    {
            pr=pr+"\nCorreo del empleado";
        }
        if(IEfecha_nacimiento == null)    {
            pr=pr+"\nFecha de nacimiento";
        }
        if(IEpuesto==0)    {
            pr=pr+"\nPuesto";
        }
        if(!ALERTA.valcurp(IEcurp))    {
            pr=pr+"\nCURP";
        }
        if(!ALERTA.valnss(IEnss))    {
            pr=pr+"\nNúmero de Seguridad Social";
        }
        if(!ALERTA.valcel(IEcelular))    {
            pr=pr+"\nCelular";
        }
        if(!ALERTA.valtel(IEtelefono_emergencia))    {
            pr=pr+"\nTeléfono de emergencia";
        }
        if(!ALERTA.valtext(IEnombre_contacto))    {
            pr=pr+"\nNombre del contacto";
        }
        if(!ALERTA.valtext(IEapellido_paterno_contacto))    {
            pr=pr+"\nApellido paterno del contacto";
        }
        if(!ALERTA.valtext(IEapellido_materno_contacto))    {
            pr=pr+"\nApellido materno del contacto";
        }
        if(!ALERTA.valmail(IEcorreo_contacto)) {
            pr=pr+"\nCorreo del contacto";
        }
        if(!ALERTA.valtel(IEtelefono))   {
            pr=pr+"\nTeléfono";
        }
        if(!ALERTA.valrfc(IErfc))    {
            pr=pr+"\nRFC";
        }
        if(!ALERTA.valne(IEnumero_exterior))    {
            pr=pr+"\nNúmero exterior";
        }
        if(!ALERTA.valni(IEnumero_interior))    {
            pr=pr+"\nNúmero interior";
        }
        if(ALERTA.vacio(IEcalle))    {
            pr=pr+"\nCalle";
        }
        if(!ALERTA.valtext(IEcolonia))    {
            pr=pr+"\nColonia";
        }
        if(!ALERTA.valcp(this.txtIEcodigo_postal.getText().trim()))    {
            pr=pr+"\nCódigo Postal";
        }
        if(IEalcaldia==0)    {
            pr=pr+"\nAlcaldía";
        }
        if(!(ALERTA.valtext(IEnombre_de_empleado)&&ALERTA.valtext(IEapellido_paterno_empleado)&&ALERTA.valtext(IEapellido_materno_empleado)&&
                ALERTA.valmail(IEcorreo)&&IEpuesto!=0&&ALERTA.valcurp(IEcurp)&&ALERTA.valnss(IEnss)&&ALERTA.valcel(IEcelular)&&
                ALERTA.valtel(IEtelefono_emergencia)&&ALERTA.valtext(IEnombre_contacto)&&ALERTA.valtext(IEapellido_paterno_contacto)&&
                ALERTA.valtext(IEapellido_materno_contacto)&&ALERTA.valmail(IEcorreo_contacto)&&ALERTA.valtel(IEtelefono)&&
                ALERTA.valrfc(IErfc)&&ALERTA.valne(IEnumero_exterior)&&ALERTA.valni(IEnumero_interior)&&!ALERTA.vacio(IEcalle)&&
                ALERTA.valtext(IEcolonia)&&ALERTA.valcp(this.txtIEcodigo_postal.getText().trim())&&IEalcaldia!=0))    {
            JOptionPane.showMessageDialog(null, "Revice los siguientes campos e inténtelo de nuevo: "+pr, "Datos incorrectos", 2);
        }
    }//GEN-LAST:event_btnIEguardarActionPerformed

    private void tgbIEvigenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgbIEvigenteActionPerformed
        if(tgbIEvigente.isSelected())   {
            tgbIEvigente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_check_box_black_18dp.png")));
        }
        else    {
            tgbIEvigente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_check_box_outline_blank_black_18dp.png")));
        }
    }//GEN-LAST:event_tgbIEvigenteActionPerformed

    private void txtIEtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIEtelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIEtelefonoActionPerformed

    private void txtIEapellido_paterno_contactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIEapellido_paterno_contactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIEapellido_paterno_contactoActionPerformed

    private void cboxIEpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxIEpuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxIEpuestoActionPerformed

    private void cboxIEpaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxIEpaisActionPerformed

    }//GEN-LAST:event_cboxIEpaisActionPerformed

    private void cboxIEestadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxIEestadoItemStateChanged
        this.cboxIEalcaldia.removeAllItems();
        this.cboxIEalcaldia.addItem("Seleccione la alcaldía");
        ConexionMySQL cmysql = new ConexionMySQL();
        Connection conec = (Connection) cmysql.Conectar();
        
        try {
            Statement st=conec.createStatement();
            ResultSet rs = st.executeQuery("SELECT alcaldia FROM tbl_alcaldia WHERE claveCiudad = "+cboxIEestado.getSelectedIndex());
            while (rs.next())   {
                this.cboxIEalcaldia.addItem(rs.getString("alcaldia"));
            }
        } catch(Exception ex)   {
            JOptionPane.showMessageDialog(null,ex,"SQL error",2);
        }
    }//GEN-LAST:event_cboxIEestadoItemStateChanged

    private void cboxIEpaisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxIEpaisItemStateChanged
        this.cboxIEestado.removeAllItems();
        this.cboxIEestado.addItem("Seleccione un estado");
        ConexionMySQL cmysql = new ConexionMySQL();
        Connection conec = (Connection) cmysql.Conectar();
        
        try {
            Statement st=conec.createStatement();
            ResultSet rs = st.executeQuery("SELECT estado FROM tbl_estado WHERE clavePais = "+cboxIEpais.getSelectedIndex());
            while (rs.next())   {
                this.cboxIEestado.addItem(rs.getString("estado"));
            }
        } catch(Exception ex)   {
            JOptionPane.showMessageDialog(null,ex,"SQL error",2);
        }
    }//GEN-LAST:event_cboxIEpaisItemStateChanged

    private void txtIEnombre_de_empleadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIEnombre_de_empleadoFocusLost
        IEn = ALERTA.valtext(this.txtIEnombre_de_empleado.getText().trim())&&!this.txtIEnombre_de_empleado.getText().equals("");
    }//GEN-LAST:event_txtIEnombre_de_empleadoFocusLost

    private void txtIEapellido_paterno_empleadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIEapellido_paterno_empleadoFocusLost
        IEap = ALERTA.valtext(this.txtIEapellido_paterno_empleado.getText().trim())&&!this.txtIEapellido_paterno_empleado.getText().equals("");
    }//GEN-LAST:event_txtIEapellido_paterno_empleadoFocusLost

    private void txtIEapellido_materno_empleadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIEapellido_materno_empleadoFocusLost
        IEam = ALERTA.valtext(this.txtIEapellido_materno_empleado.getText().trim())&&!this.txtIEapellido_materno_empleado.getText().equals("");
    }//GEN-LAST:event_txtIEapellido_materno_empleadoFocusLost

    private void txtIEcurpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIEcurpMouseClicked
        IEfn = this.dcIEfecha_nacimiento.getDate()!=null;
        if(IEn&&IEap&&IEam&&IEfn)    {
            System.out.println(ffecha.format(this.dcIEfecha_nacimiento.getDate()));
            this.txtIEcurp.setText(txtIEapellido_paterno_empleado.getText().substring(0,2).toUpperCase()+
                    txtIEapellido_materno_empleado.getText().substring(0,1).toUpperCase()+
                    txtIEnombre_de_empleado.getText().substring(0,1).toUpperCase()+
                    ffecha.format(this.dcIEfecha_nacimiento.getDate()).substring(2,4)+
                    ffecha.format(this.dcIEfecha_nacimiento.getDate()).substring(5,7)+
                    ffecha.format(this.dcIEfecha_nacimiento.getDate()).substring(8,10)+
                    "MDF"+
                    txtIEapellido_paterno_empleado.getText().substring(2,3).toUpperCase()+
                    txtIEapellido_materno_empleado.getText().substring(2,3).toUpperCase()+
                    txtIEnombre_de_empleado.getText().substring(2,3).toUpperCase()+
                    "A9");
        }
    }//GEN-LAST:event_txtIEcurpMouseClicked

    private void txtIErfcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIErfcMouseClicked
        IEfn = this.dcIEfecha_nacimiento.getDate()!=null;
        if(IEn&&IEap&&IEam&&IEfn)    {
            this.txtIErfc.setText(txtIEapellido_paterno_empleado.getText().substring(0,2).toUpperCase()+
                    txtIEapellido_materno_empleado.getText().substring(0,1).toUpperCase()+
                    txtIEnombre_de_empleado.getText().substring(0,1).toUpperCase()+
                    ffecha.format(this.dcIEfecha_nacimiento.getDate()).substring(2,4)+
                    ffecha.format(this.dcIEfecha_nacimiento.getDate()).substring(5,7)+
                    ffecha.format(this.dcIEfecha_nacimiento.getDate()).substring(8,10)+
                    "QG7");
        }
    }//GEN-LAST:event_txtIErfcMouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIEcancelar;
    private javax.swing.JButton btnIEfoto;
    private javax.swing.JButton btnIEguardar;
    private javax.swing.JComboBox<String> cboxIEalcaldia;
    private javax.swing.JComboBox<String> cboxIEciudad;
    private javax.swing.JComboBox<String> cboxIEestado;
    private javax.swing.JComboBox<String> cboxIEpais;
    private javax.swing.JComboBox<String> cboxIEpuesto;
    private com.toedter.calendar.JDateChooser dcIEfecha_nacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblIEno_vigente;
    private javax.swing.JLabel lblIEvigente;
    private javax.swing.JToggleButton tgbIEvigente;
    private javax.swing.JTextField txtIEapellido_materno_contacto;
    private javax.swing.JTextField txtIEapellido_materno_empleado;
    private javax.swing.JTextField txtIEapellido_paterno_contacto;
    private javax.swing.JTextField txtIEapellido_paterno_empleado;
    private javax.swing.JTextField txtIEcalle;
    private javax.swing.JTextField txtIEcelular;
    private javax.swing.JTextField txtIEcodigo_postal;
    private javax.swing.JTextField txtIEcolonia;
    private javax.swing.JTextField txtIEcorreo;
    private javax.swing.JTextField txtIEcorreo_contacto;
    private javax.swing.JTextField txtIEcurp;
    private javax.swing.JTextField txtIEnombre_contacto;
    private javax.swing.JTextField txtIEnombre_de_empleado;
    private javax.swing.JTextField txtIEnss;
    private javax.swing.JTextField txtIEnumero_exterior;
    private javax.swing.JTextField txtIEnumero_interior;
    private javax.swing.JTextField txtIErfc;
    private javax.swing.JTextField txtIEtelefono;
    private javax.swing.JTextField txtIEtelefono_emergencia;
    // End of variables declaration//GEN-END:variables
}
