version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sasercon-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-14p7uc1qf1lj2"
s3_prefix = "sasercon-backend"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
